/**
 * Architecture-doc generation for the Arch Lens backend. Two entry points:
 *   - generateFullDocs: one LLM pass writes a complete docs/architecture.md
 *     (concept / sequence / interaction / dependency / ER / catalog sections).
 *   - generateDocSection: one dimension regenerated on demand (per-tab "AI
 *     generate"); sequence/interaction also write structured caches the
 *     figures render directly.
 * A generated file carries a marker header; a pre-existing hand-written
 * architecture.md is never overwritten — the generated doc lands in
 * docs/architecture.generated.md instead.
 * @module @deepseek-ai/dsh-arch-lens-backend/src/docsgen
 */
import type { Context } from '@deepseek-ai/cordis';
import type { FileSystem } from '@deepseek-ai/dsh-fs';
import type { SandboxExecutionPolicy } from '@deepseek-ai/dsh-sandbox';
import type { CodeIndexResult } from '@deepseek-ai/dsh-code-index';
/** Section titles per dimension, used as `##` headings in the doc. */
export declare const SECTION_TITLES: Record<DocKind, string>;
/** Supported doc sections (one per figure/tab dimension). */
export type DocKind = 'concepts' | 'seq' | 'interaction' | 'deps' | 'er' | 'catalog';
/** Resolve the doc target: primary when absent or already generated; else the AI variant. */
export declare function resolveDocTarget(fs: FileSystem, root: string): Promise<string>;
/** Bounded summary lines of the code index for prompts (shared with flow.ts). */
export declare function indexSummary(index: CodeIndexResult): string;
/**
 * One LLM generation call with the standard config contract (shared with
 * flow.ts). The output cap is optional: omitted, the request inherits the
 * adapter's Config-owned default maxTokens instead of a local literal.
 */
export declare function llmText(ctx: Context, prompt: string, temperature: number, maxTokens?: number): Promise<string>;
/**
 * Generate one doc section on demand (per-tab "AI generate"). Sequence and
 * interaction also write structured caches for their figures.
 * @param ctx - host context.
 * @param fs - filesystem service.
 * @param root - workspace root.
 * @param index - code index result.
 * @param language - role language.
 * @param kind - section dimension.
 * @returns the doc target path, or an error.
 */
export declare function generateDocSection(ctx: Context, fs: FileSystem, root: string, index: CodeIndexResult, language: string, kind: DocKind, sandboxPolicy?: SandboxExecutionPolicy): Promise<{
    path: string;
} | {
    error: string;
}>;
/**
 * Generate the complete architecture doc in one pass (global button).
 * @param ctx - host context.
 * @param fs - filesystem service.
 * @param root - workspace root.
 * @param index - code index result.
 * @param language - role language.
 * @returns the doc target path, or an error.
 */
export declare function generateFullDocs(ctx: Context, fs: FileSystem, root: string, index: CodeIndexResult, language: string, sandboxPolicy?: SandboxExecutionPolicy): Promise<{
    path: string;
} | {
    error: string;
}>;
/**
 * Build the LLM induction prompt for the main-flow sequence figure: the
 * project-core main flow, entry → core loop → key capabilities → output.
 * The main line is pinned by name: entry packages (with entry files) start
 * the flow and the most-imported packages (in-degree over source imports)
 * form the core it must pass through. Every from/to must be a real package
 * id from the index summary (the anti-fabrication clause), so the figure
 * stays code-grounded.
 * @param index - code index result.
 * @param language - output language.
 * @returns the prompt text.
 */
export declare function seqInductionPrompt(index: CodeIndexResult, language: string): string;
/**
 * Structured figure data for the sequence/interaction tabs, generated by LLM
 * from the code index and cached per language.
 * @param ctx - host context.
 * @param fs - filesystem service.
 * @param root - workspace root.
 * @param index - code index result.
 * @param language - role language.
 * @param kind - 'seq' or 'interaction'.
 * @returns the parsed structured data, or an error.
 */
export declare function writeStructuredCache(ctx: Context, fs: FileSystem, root: string, index: CodeIndexResult, language: string, kind: 'seq' | 'interaction', sandboxPolicy?: SandboxExecutionPolicy): Promise<unknown[] | {
    error: string;
}>;
/**
 * Read the structured figure cache for a language, if present.
 * @param fs - filesystem service.
 * @param root - workspace root.
 * @param language - role language.
 * @param kind - 'seq' or 'interaction'.
 * @returns the cached array, or null.
 */
export declare function readStructuredCache(fs: FileSystem, root: string, language: string, kind: 'seq' | 'interaction'): Promise<unknown[] | null>;
//# sourceMappingURL=docsgen.d.ts.map