/**
 * Arch Lens backend host service: workspace graph scanning, component detail
 * projection, and answer-level note recording. Read-only graph/component/notes
 * methods cross to the browser via Typert Remote; note file WRITES have exactly
 * one path — the session/event listener below. notePending only stages in-memory
 * question metadata; it never touches the file.
 * @module @deepseek-ai/dsh-arch-lens-backend
 */
import { Context, Service } from '@deepseek-ai/cordis';
import { TypertRemoteService } from '@deepseek-ai/dsh-typert-protocol';
import s from '@deepseek-ai/schemastery';
import type { DocKind, FollowUpKind, FollowUpResult } from './types.ts';
import type { ArchLensCodeInsight, ArchLensComponentDetail, ArchLensConceptNode, ArchLensCoreGraph, ArchLensFlowResult, ArchLensGraph, ArchLensNotesResult, ArchLensProgressResult, ArchLensPromptConfig, ArchLensPromptConfigResult, ArchLensSequenceResult, FlowAngle, GenerationStatus, LlmStatsSnapshot, RegenerateFigureResult, WorkspaceChanges } from './types.ts';
export * from './types.ts';
/** Optional deployment configuration. */
export interface Config {
    /** Note file name in the workspace root (default ARCH-NOTES.md). */
    notesFile?: string;
}
declare module '@deepseek-ai/cordis' {
    interface Context {
        archLens: ArchLensService;
    }
}
/**
 * The Arch Lens backend Remote service (`ctx.archLens`).
 */
export declare class ArchLensService extends TypertRemoteService {
    static inject: string[];
    /** Loader validation for the optional note file name. */
    static Config: s<Config>;
    private readonly notesFile;
    /** Per-workspace scan cache: keyed by the resolved workspace root, so
     * re-loading the desk on the same workspace never rescans, while switching
     * to a different workspace rescans automatically on the next graph(). */
    private graphCaches;
    /** One in-flight read (root + promise) so concurrent callers share one
     * cache read per root; a read of another root can run alongside. */
    private graphInFlight;
    private pending;
    /** One staged session-driven figure request (🤖 AI 生成 via 会话回合):
     * matched by figId in the agent's answer, written to the figure cache. */
    private pendingFigure;
    /** One staged CUSTOM figure request (🎨 动态出图): matched by figId in the
     * agent's answer, captured into customFigures[figureId]. `figureId` is the
     * stable scene id (`dynamic-N`, per-workspace counter) the panel locks on
     * save; a follow-up re-uses it, a new scene allocates a fresh one. */
    private pendingCustomFigure;
    /** All custom figures known this session, keyed by scene id: generated by
     * the panel OR restored from disk. `saved` reflects whether the CURRENT
     * content is persisted (a follow-up re-render flips it back to false). */
    private customFigures;
    /** In-flight code-index load per root: CONCURRENT figure RPCs share ONE
     * indexWorkspace call instead of each re-loading/re-parsing the workspace
     * (the disk cache already avoids re-scanning source; this dedups the load). */
    private indexInFlight;
    /** Shared workspace index load: concurrent calls for the SAME root await the
     * same in-flight promise (dedup); sequential calls behave exactly like a
     * plain indexWorkspace. The on-disk index cache is bound to the current
     * facts version (「↻ 重新扫描」's generatedAt): an unknown version (0) makes
     * the provider neither read nor persist, and a mismatched envelope on disk
     * triggers exactly one forced rebuild (defense in depth).
     * @throws when the codeIndex service is unavailable. */
    private indexWorkspaceShared;
    /** Session whose cwd anchors the workspace root; null falls back to the sandbox policy. */
    private targetSessionId;
    /**
     * @param ctx - host context carrying fs and sandboxPolicy.
     * @param config - optional notes file name.
     */
    constructor(ctx: Context, config?: Config);
    /** Resolve the workspace root from the target session's cwd, else the sandbox policy. */
    private resolveRoot;
    /** Snapshot the session's cumulative token usage (the tokenUsage projection
     * from token-meter), or undefined when the session or projection is
     * unavailable. The delta between two snapshots around one staged request
     * attributes that request's provider-reported spend to the arch-lens
     * action (AI 生成 / 动态出图 / 讲解 run inside the session's agent turn). */
    private sessionUsageSnapshot;
    /** Attribute one staged session-driven request's token spend (delta between
     * the staged and the current session tokenUsage) to the LLM ledger. */
    private recordSessionUsage;
    /** In-flight follow-up redraw AbortControllers per workspace root: the
     * panel's「取消」button (while a redraw is running) aborts the matching
     * controller so the LLM stream stops and the cache is never overwritten. */
    private followUpAbort;
    /** In-flight full-docs generation per workspace root: repeated「📄 一键生成
     * 文档」clicks (or parallel RPCs) while one is running reuse the SAME
     * promise — the LLM work runs exactly once per root, later calls share its
     * result instead of re-generating. */
    private docInFlight;
    /** Scan (with cache) the workspace package tree; concurrent callers share
     * one scan per root. Cache-first: a previously scanned workspace (any
     * session of it) resolves instantly; only a new root triggers a scan.
     * The scan graph is ALSO persisted to `index/.arch-lens-graph.json` under the
     * workspace root, so reopening the desk after a host restart serves the
     * cached graph instead of re-walking the filesystem. refresh() marks the
     * disk copy invalid before it rescans (the FileSystem has no delete).
     * READ-ONLY: never scans. Facts (scan graph + code index) are built ONLY
     * by rescan (refresh) — opening the panel / switching tabs never walks the
     * filesystem. No disk cache ⇒ returns null.
     */
    private graph;
    /** Read the persisted scan graph; null when absent, invalidated or foreign. */
    private graphFromDisk;
    /** Persist a fresh scan graph (non-fatal on failure) and return the new
     * facts version (generatedAt) written, or 0 when the write failed. */
    private writeGraphDisk;
    /** Graph read for internal consumers: null (no facts built yet) collapses
     * to an error so callers never touch undefined nodes/edges. */
    private requireGraph;
    /**
     * Duty facts for figure prompts — the 「各包职责」 section is assembled
     * HOST-side from disk state (review verdict C): versioned AI summaries
     * (readDutySummaries: miss/stale-version → null, NEVER generates) → scanned
     * blurbs. Making the link a pure function of disk state means 「职责→出图」
     * holds regardless of whether the catalog tab was ever opened — no timing
     * hole, no second copy of the priority rule (single source: duty-facts.ts
     * leaf). The old client-supplied LEGACY fallback map is gone: the disk chain
     * is the only fact source, so a second copy could only diverge.
     */
    private dutyFactsForFigure;
    /**
     * The scanned workspace graph (read-only cache; null when no rescan has
     * built facts yet). Facts are established by refresh() (重新扫描).
     * @returns graph, null when no disk cache, or an error.
     */
    remoteGraph(): Promise<ArchLensGraph | null | {
        error: string;
    }>;
    /**
     * Rescan = REBUILD EVERY fact source (the ONLY place facts are built):
     * invalidate the scan graph, re-index the code-index, invalidate the AI
     * caches, then scan the workspace and persist a fresh graph (new
     * generatedAt = new facts version). Opening the panel / switching tabs
     * NEVER scans — they read caches only.
     * Layer-1 change detection: when the file manifest shows NO file changed
     * since the last rescan, every cache is still valid and the rebuild is
     * skipped entirely — the existing graph is returned as-is.
     * @returns the fresh scan graph (or null when none exists yet) plus
     *   whether a rebuild actually ran.
     */
    remoteRefresh(): Promise<{
        graph: ArchLensGraph;
        changed: true;
        changes: WorkspaceChanges;
    } | {
        graph: ArchLensGraph | null;
        changed: false;
        changes: null;
    } | {
        error: string;
    }>;
    /**
     * Refresh only the code-index facts (in-memory + disk invalidated). Used by
     * "refresh this figure": the figure then re-derives from a fresh index.
     * @returns acknowledgement.
     */
    remoteRefreshIndex(): Promise<{
        ok: true;
    } | {
        error: string;
    }>;
    /**
     * 「全量重建」: regenerate AI figures from the CURRENT facts. 智能增量
     * (incremental=true, 前端「全量重建」/「变动更新」按钮的默认路径)：每张
     * 实体级图先检查缓存是否失效（v ≠ 当前 factsVersion 或缺失），失效才
     * force=true 重绘，未失效直接跳过——重新扫描已做精确失效，所以这里只补
     * 涉及变动包的图；全部有效时零 LLM、秒回。incremental=false 保持旧语义
     * （无条件全部重绘）。方法级（-methods）不在此路径（按需生成）。
     * @param request - role language + 是否智能增量。
     * @returns rebuilt/skipped 图清单，或第一个生成错误（所有步骤都跑）。
     */
    remoteGenerateAll(request: {
        language?: string;
        incremental?: boolean;
    }): Promise<{
        ok: true;
        rebuilt: string[];
        skipped: string[];
    } | {
        error: string;
    }>;
    /**
     * Point the desk's data source at one session's workspace. This is the
     * official wire name (kept for harness-contract compatibility) but its
     * SEMANTICS are "load, never invalidate": only the target session id is
     * set and no cache is touched. The scan cache is keyed by workspace root,
     * so re-loading the same workspace (reopening the panel, switching between
     * its sessions) is instant, while a different workspace rescans
     * automatically on the next graph() call. Explicit invalidation stays
     * exclusively on refresh().
     * @param sessionId - target session id, or null for the policy root.
     * @returns acknowledgement.
     */
    remoteSetSession(sessionId: string | null): Promise<{
        ok: true;
    }>;
    /**
     * Fold the workspace's persisted LLM ledger (`index/.arch-lens-llm-stats.json`)
     * into the running accounting. The disk file is treated as the historical
     * ledger and adoption is once-per-process (llmStatsAdopted gate), so this
     * is safe to call from every entry point that runs before the first write.
     */
    private adoptLlmStats;
    /** Invalidate the code-index for the workspace (no-op when unavailable). */
    private refreshCodeIndex;
    /**
     * Ensure the on-disk code-index envelope is valid against the CURRENT facts
     * version, rebuilding through the shared loader when it is not (blanked by
     * provider.refresh, stale, or lost to a crashed rescan).
     *
     * Best-effort AND time-boxed: a full-workspace parse can run for minutes on
     * a large monorepo, far beyond the rescan RPC budget, so the shared loader
     * is started (or joined if already in flight) and awaited only up to a cap.
     * Small workspaces finish inline so the call graph opens on the first try;
     * big ones keep building in the background — the in-flight promise survives
     * on `indexInFlight`, writes the envelope when done, and later reads serve
     * from it. A rebuild failure never fails the caller's rescan: the graph
     * facts are already established and the affected tabs keep their rescan hint.
     * @param root - workspace root.
     */
    private ensureIndexEnvelope;
    /**
     * Invalidate AI figure caches (concept tree / sequence / events / flow /
     * core / analysis). Since the versioned-cache change the DISK copies are
     * NOT touched: a rescan rebuilds the scan graph with a fresh generatedAt
     * (facts version), and every figure cache records the version it was
     * generated against — readers refuse a mismatched version and regenerate.
     * Physical clearing was the cause of "reopening the panel is slow": it
     * threw away caches that were still valid across page reloads.
     */
    private removeAICaches;
    /**
     * Detail projection for one package. The graph carries precomputed details,
     * so this is a plain lookup (kept as a Remote for compatibility).
     * @param request - package id.
     * @returns detail or error.
     */
    remoteComponent(request: {
        id: string;
    }): Promise<ArchLensComponentDetail | {
        error: string;
    }>;
    /**
     * The note file listing, newest first.
     * @returns notes listing or an error.
     */
    remoteNotes(): Promise<ArchLensNotesResult | {
        error: string;
    }>;
    /**
     * Mermaid dependency flowchart for the scanned graph.
     * @returns flowchart source or an error.
     */
    remoteMermaidDeps(): Promise<{
        kind: 'flowchart';
        source: string;
    } | {
        error: string;
    }>;
    /**
     * Mermaid ER diagram of package relationships for the scanned graph.
     * @returns erDiagram source or an error.
     */
    remoteMermaidEr(): Promise<{
        kind: 'erDiagram';
        source: string;
    } | {
        error: string;
    }>;
    /**
     * Mermaid diagrams over the code-index imports: source-level dependency
     * edges (real imports) instead of npm peerDependencies. Falls back to the
     * scanned-graph variants when the codeIndex service or a language is absent.
     * @param request - diagram kind.
     * @returns mermaid source or an error.
     */
    remoteMermaidIndexed(request: {
        kind: 'flowchart' | 'erDiagram';
    }): Promise<{
        kind: 'flowchart' | 'erDiagram';
        source: string;
    } | {
        error: string;
    }>;
    /**
     * 「调用关系图」真实数据源 — READ ONLY: the real cross-package import
     * reference edges from the versioned code-index disk cache (facts written
     * by 「↻ 重新扫描」 only, never by AI; version binding lives in
     * `readIndexFacts`). Pure cache read: no index-service call, no LLM. Edges
     * are returned in message shape so the client renders them with the same
     * call-graph view.
     * @param request - role language for edge labels.
     * @returns package-level edges, or an error telling the user to rescan first.
     */
    remoteCallGraph(request: {
        language?: string;
    }): Promise<{
        ok: true;
        edges: Array<{
            from: string;
            to: string;
            label: string;
        }>;
    } | {
        error: string;
    }>;
    /**
     * Core-flow diagram (deps/ER overview) — READ ONLY: built from the cached
     * core selection + the scanned graph; null when no core cache exists.
     * Generation (LLM selection) is WRITE-path only (「🤖 AI 生成」 /
     * regenerateFigure). Never walks the code index.
     * @param request - diagram kind, role language.
     * @returns mermaid source and core selection, null, or an error.
     */
    remoteMermaidCore(request: {
        kind: 'flowchart' | 'erDiagram';
        language?: string;
        methodLevel?: boolean;
    }): Promise<{
        kind: 'flowchart' | 'erDiagram';
        source: string;
        core: ArchLensCoreGraph;
    } | null | {
        error: string;
    }>;
    /**
     * 架构概览 (rule-built) — READ ONLY (D2): built from the cached core
     * selection + the scanned graph; null when no core cache exists. There is
     * NO rule fallback on read — facts appear only after a rescan plus the
     * user's generate action (「🤖 AI 生成」 / regenerateFigure writes the core
     * cache). Never walks the code index.
     * @param request - role language.
     * @returns the overview mermaid + core selection, null, or an error.
     */
    remoteOverviewFigure(request: {
        language?: string;
    }): Promise<{
        title: string;
        mermaid: string;
        core: ArchLensCoreGraph;
    } | null | {
        error: string;
    }>;
    /** Shared codeIndex accessor for the concept/docs remotes. The optional
     * third `factsVersion` argument binds the provider's disk cache to the
     * single change anchor (see indexWorkspaceShared). */
    private codeIndexService;
    /**
     * Session-scoped sandbox policy for every file write: the fs sandbox
     * derives its workspace-write containment root from the calling session's
     * cwd — the same root this service writes to — so passing it approves the
     * writes.
     */
    private sessionPolicy;
    /**
     * Pre-flight write check for the LLM-generating write paths (generateAll,
     * AI 生成, 追问重画, 文档, rescan rebuild): when the session sandbox is
     * read-only every cache write would be denied — refusing BEFORE the (often
     * minutes-long) LLM passes saves the user from "生成跑完了但一个缓存都没写
     * 进去" (the symptom reported from a read-only generateAll). Callers return
     * the message as their error result.
     * @returns an error message when writes are impossible, null when OK.
     */
    private ensureWritable;
    /**
     * Concept hierarchy — READ ONLY: serve the versioned cache; null when
     * absent/stale. Generation (doc extraction / LLM induction / cache write)
     * happens ONLY through the write paths (「🤖 AI 生成」 figurePrompt /
     * regenerateFigure). Opening the panel or switching tabs never generates.
     * @param request - role language and method-level cache variant.
     * @returns concept-tree nodes, null when no matching cache, or an error.
     */
    remoteConceptTree(request: {
        language?: string;
        methodLevel?: boolean;
    }): Promise<ArchLensConceptNode[] | null | {
        error: string;
    }>;
    /**
     * Generate the complete architecture doc (global button) — 阶段 4 组装链
     * (D8)：文档正文【零 LLM】，全部章节由图缓存渲染；某节对应图缺失/过期时，
     * 先经该图自己的构建链补建（缓存→文档→档案→LLM，统一写路径回缓存），再
     * 组装。文档不再反哺任何图缓存（旧"文档后补写/重建概念树"回灌已删）。
     * @param request - role language.
     * @returns the doc path or an error.
     */
    remoteGenerateDocs(request: {
        language?: string;
    }): Promise<{
        path: string;
    } | {
        error: string;
    }>;
    /**
     * Regenerate one doc section on demand (per-tab "AI 生成") — 组装链单节版：
     * 该节的图走注册表缓存/构建链，正文渲染零 LLM，merge 进生成文档的对应
     * `## 标题` 节。
     * @param request - section kind and role language.
     * @returns the doc path or an error.
     */
    remoteGenerateDocSection(request: {
        kind: DocKind;
        language?: string;
    }): Promise<{
        path: string;
    } | {
        error: string;
    }>;
    /**
     * Structured figure data for the sequence tab — READ ONLY: serve the
     * versioned cache; null when absent/stale. The static call-graph, doc
     * extraction and LLM induction stages are WRITE-path only (「🤖 AI 生成」 /
     * regenerateFigure). Opening the panel or switching tabs never generates.
     * The client renders an empty state on null.
     * @param request - role language and method-level cache variant.
     * @returns the cached figure, null, or an error.
     */
    remoteSequence(request: {
        language?: string;
        methodLevel?: boolean;
    }): Promise<ArchLensSequenceResult | null | {
        error: string;
    }>;
    /**
     * Per-tab "AI generate" (分离方案): regenerate ONE shared-profile field
     * with one trimmed-summary LLM call and return the fresh figure data. The
     * profile is updated in memory and on disk; other figures are untouched
     * (except core regeneration, which invalidates flow/seq/events — see
     * analysis.ts). The client renders the returned data directly, so a
     * per-tab generate never rewrites docs/architecture.generated.md.
     * @param request - figure kind and role language.
     * @returns the regenerated field, or an error.
     */
    remoteRegenerateFigure(request: {
        kind: 'concepts' | 'seq' | 'flow' | 'interaction' | 'deps' | 'er';
        language?: string;
        methodLevel?: boolean;
    }): Promise<RegenerateFigureResult | {
        error: string;
    }>;
    /**
     * 🔬 方法级 field regeneration: one method-summary LLM call for the figure,
     * independent of the shared (entity-level) profile. Results are written to
     * the method-level caches so a later read with the switch on reuses them.
     * @param kind - the wire figure kind (concepts/seq/flow/interaction/deps/er).
     * @param index - code index result.
     * @param language - role language.
     * @returns the regenerated field, or an error.
     */
    private regenerateFigureMethodLevel;
    /**
     * The latest assistant answer of the target session: visible text plus the
     * reasoning chain (thinking blocks). The panel shows the model's thinking
     * for the last explanation — the reasoning stays in the session message
     * (host-side projection), the client only renders a copy.
     * @param request - optional session id (defaults to the target session).
     * @returns the last assistant message's text/reasoning, or an error.
     */
    remoteLastAnswer(request: {
        sessionId?: string;
    }): Promise<{
        text: string;
        reasoning: string;
    } | {
        error: string;
    }>;
    /**
     * Live generation status of the workspace (⚙️ 生成过程 box): what the LLM
     * is currently doing — stage label, elapsed time, streamed output preview
     * (reasoning tail while thinking). Polled by the panel while a generation
     * is suspected in flight; null when nothing was generated yet.
     * @returns the live status, or null.
     */
    remoteGenerationStatus(): Promise<GenerationStatus | null>;
    /**
     * LONG-POLL push of the live generation status: resolves when the status
     * seq differs from `since` (a change just happened — throttled to a smooth
     * cadence), or after ~20s with the current snapshot (the panel re-issues
     * immediately). One in-flight request at a time delivers the generation
     * process with SSE-like latency over the regular RPC channel.
     * @param request - the client's last seen seq.
     * @returns the current status snapshot, or null when nothing was generated.
     */
    remoteGenerationStatusNext(request: {
        since?: number;
    }): Promise<{
        status: GenerationStatus;
        seq: number;
    } | null>;
    /**
     * Build the session message that asks the agent to produce ONE figure
     * (「图生成走会话」): the prompt embeds the code facts; the CLIENT sends it
     * into the current session, so the GUI's own conversation stream shows the
     * agent working in real time. This RPC stages a pendingFigure (matched by
     * figId) and returns immediately — the figure lands in the cache when the
     * agent answers, and the panel refetches it after the turn completes.
     * @param request - figure kind, role language, flow angle, 🔬 method level.
     * @returns the figId + prompt to send, or an error.
     */
    remoteFigurePrompt(request: {
        kind: 'concepts' | 'seq' | 'flow' | 'interaction' | 'deps' | 'er';
        language?: string;
        angle?: FlowAngle;
        methodLevel?: boolean;
    }): Promise<{
        figId: string;
        prompt: string;
    } | {
        error: string;
    }>;
    /**
     * Build the session message that asks the agent to draw ONE DYNAMIC detail
     * figure (「动态画图」hover drill-down): a sequence-edge drill-down (the two
     * packages' method-level call sequence) or a flow-subgraph expansion (that
     * stage as a detailed flowchart). Same session-turn contract as figurePrompt
     * — the answer is matched by figId and written to a per-target cache file
     * (`index/.arch-lens-dynamic-<kind>-<hash>[-<lang>].json`), so a generated detail
     * opens instantly on the next hover without re-generating.
     * @param request - dynamic kind, hover target, role language, and for
     *   flow-subgraph the current diagram source (context.mermaid).
     * @returns the figId + prompt to send, or an error.
     */
    remoteDynamicFigurePrompt(request: {
        kind: 'seq-edge' | 'flow-subgraph' | 'overview';
        target: {
            from?: string;
            to?: string;
            label?: string;
            stage?: string;
        };
        language?: string;
        context?: {
            mermaid?: string;
        };
    }): Promise<{
        figId: string;
        prompt: string;
    } | {
        error: string;
    }>;
    /** Read one cached dynamic figure (`index/.arch-lens-dynamic-<kind>-<hash>[-<lang>].json`),
     * or null when absent / unreadable / stale (version-bound read, D1: an
     * invalidated or outdated drill-down must NOT be served — the client's hover
     * then re-triggers generation; legacy unversioned files read as null too).
     * Shared by the read RPC and the re-drill prompt builder (same-family
     * incremental reuse). */
    private readDynamicFigureFromDisk;
    /**
     * Read one cached dynamic figure (`index/.arch-lens-dynamic-<kind>-<hash>[-<lang>].json`).
     * The panel calls this after the turn completes (and on every later hover)
     * so a generated detail opens instantly without re-generating.
     * @param request - dynamic kind, target key, role language.
     * @returns the cached diagram, or null when absent.
     */
    remoteDynamicFigure(request: {
        kind: 'seq-edge' | 'flow-subgraph' | 'overview';
        targetKey: string;
        language?: string;
    }): Promise<{
        title: string;
        diagram: string;
        kind: 'seq-edge' | 'flow-subgraph' | 'overview';
        targetKey: string;
    } | null | {
        error: string;
    }>;
    /**
     * L2.5 渲染即校验：the browser's version-matched mermaid is the ONLY syntax
     * authority (the host has no DOM — a mermaid import there dies on DOMPurify;
     * nothing here may ever stamp a figure "valid"). Drill-down figures are
     * auto-persisted at capture, so a syntax-broken diagram the sanitizer
     * could not safely repair would otherwise fail EVERY later hover forever:
     * syntax rot is independent of the fact version the cache is bound to.
     * The panel reports the first render failure and this deletes that disk
     * cache (unlink, same removal precedent as customFigureDelete) — the next
     * hover honestly reads the empty state and regenerates. Zero-LLM
     * self-cleaning; the inline error stays visible to the user.
     * @param request - dynamic kind, target key, role language (cache name).
     * @returns `{ ok: true, removed }` (removed=false: already absent) or error.
     */
    remoteDynamicFigureFailed(request: {
        kind: 'seq-edge' | 'flow-subgraph' | 'overview';
        targetKey: string;
        language?: string;
    }): Promise<{
        ok: true;
        removed: boolean;
    } | {
        error: string;
    }>;
    /**
     * Build the session message for the CUSTOM figure branch (「🎨 动态出图」): the
     * user types ANY request ("存图的逻辑，怎么存的、存哪、怎么读的…") and the agent
     * draws a matching diagram PLUS a short summary. Same session-turn contract
     * as dynamicFigurePrompt — the answer is matched by figId, captured into
     * `customFigures[figureId]`, and NOT persisted automatically: the panel's
     * 保存 button locks the scene id to disk explicitly.
     * SCENE ID: when `figureId` is given (a follow-up on an existing scene) it is
     * reused and the existing figure is embedded as context; otherwise a new
     * per-workspace id `dynamic-N` is allocated for a brand-new scene.
     * @param request - the user's figure request text, optional target figureId
     *   (follow-up), and role language — the duty section is assembled host-side
     *   (dutyFactsForFigure), so AI-generated summaries reach the prompt with
     *   no client state involved.
     * @returns the figId + scene figureId + prompt to send, or an error.
     */
    remoteCustomFigurePrompt(request: {
        text: string;
        figureId?: string;
        language?: string;
    }): Promise<{
        figId: string;
        figureId: string;
        prompt: string;
    } | {
        error: string;
    }>;
    /**
     * Read ONE custom figure scene: in-memory first (this session's generated or
     * restored content), then the saved disk file (marked `saved: true`). The
     * panel calls this after a turn completes (to render the freshly drawn
     * figure) and when the user selects a scene in the list.
     * FALLBACK (no figureId): return the newest in-memory figure, else the
     * newest saved one, so a plain panel reopen restores something useful.
     * @returns the custom figure (figureId, title, diagram, summary, text),
     *   null when nothing matches, or an error.
     */
    remoteCustomFigure(request: {
        figureId?: string;
    }): Promise<{
        figureId: string;
        title: string;
        diagram: string;
        summary: string;
        text: string;
        saved?: boolean;
    } | null | {
        error: string;
    }>;
    /** Parse one `.arch-lens-draw-*.json` file into its figure record. figureId
     * comes from the file's `figureId` field when present, else the file name
     * (`dynamic-N` for scene saves, the hash part for legacy text-hash saves).
     * Returns null for unreadable, diagram-less, or tombstoned (deleted) files. */
    private drawFileRecord;
    /** Scan `index/` then the workspace root (legacy saves) for every saved
     * custom figure file. Tombstoned (deleted) files are filtered out. */
    private readSavedDraws;
    /** Read ONE saved custom figure by figureId, or null. */
    private readDrawFromDisk;
    /** Newest saved custom figure across disk (memory lost on restart), or null. */
    private readNewestDraw;
    /** Next free per-workspace scene id: `dynamic-<maxExisting+1>`. Scans raw
     * file names (INCLUDING tombstoned ones) plus memory, so deleted numbers
     * never get reused. */
    private allocateFigureId;
    /** Cache file name for a scene figure: `index/.arch-lens-draw-<figureId>[-<lang>].json`. */
    private drawFileName;
    /**
     * List every custom figure scene: saved ones from disk (saved: true) merged
     * with this session's memory figures (unsaved ones show saved: false so the
     * panel can offer 保存). Ordered dynamic-N ascending, then legacy hashes.
     * @returns the scene list (figureId, title, text, saved), or an error.
     */
    remoteCustomFigureList(): Promise<Array<{
        figureId: string;
        title: string;
        text: string;
        saved: boolean;
        savedAt?: string;
    }> | {
        error: string;
    }>;
    /**
     * 「🔧 按报错修复重画」(L3): the panel reports the RENDERER's parse error for a
     * memory scene figure; this stages a grammar-only repair turn through the
     * SAME session-turn capture pipeline as customFigurePrompt. The client sends
     * ONLY `{ figureId, error }` — the broken source is taken from the HOST copy
     * (single source of truth; the client re-sanitizes on render so the two
     * agree), and a FRESH figId nonce is minted while the LOCKED scene figureId
     * is reused, so the fix overwrites the same scene slot on capture. No
     * scan-facts replay (the facts stand in the broken diagram; replaying the
     * index would burn tokens and invite semantic drift). Manual-only: this is
     * never called automatically — the user clicks, spending one turn.
     * @param request - locked scene figureId + the renderer's error text.
     * @returns figId + figureId + prompt to send, or an error.
     */
    remoteFigureRepairPrompt(request: {
        figureId: string;
        error: string;
    }): Promise<{
        figId: string;
        figureId: string;
        prompt: string;
    } | {
        error: string;
    }>;
    /**
     * Persist a scene figure — 图 AND 概要 — to
     * `index/.arch-lens-draw-<figureId>[-<lang>].json`, LOCKING the scene id
     * (replacing the old text-hash naming). The only way a custom figure lands
     * on disk; a follow-up re-render marks it unsaved again until 保存 re-locks.
     * @param request - target figureId + role language (cache-name suffix).
     * @returns `{ ok: true, path }` or an error.
     */
    remoteSaveCustomFigure(request: {
        figureId: string;
        language?: string;
    }): Promise<{
        ok: true;
        path: string;
    } | {
        error: string;
    }>;
    /**
     * Delete a scene figure for REAL: every disk file (all language variants in
     * `index/` and the legacy root location) is physically removed via
     * node:fs/promises unlink — the fs service has no remove, so the resolved
     * target's process path is unlinked directly. Memory entry dropped. (Files
     * tombstoned by an older build are still filtered on read.)
     * @returns `{ ok: true }` or an error.
     */
    remoteCustomFigureDelete(request: {
        figureId: string;
    }): Promise<{
        ok: true;
    } | {
        error: string;
    }>;
    /**
     * 原地追问重画：对某个 tab 的主图（flow/seq/concepts/events/core/overview）
     * 做一次带追问上下文的重新生成，结果覆写同一缓存并返回新图数据；客户端
     * 直接回填该 tab 状态，图就原地更新（不画到「动态出图」）。
     * @param request - 图类型、语言、流程视角（flow）、方法级开关、追问文本。
     * @returns 与对应 tab 正常 RPC 相同形状的新图数据，或错误。
     */
    remoteFigureFollowUp(request: {
        kind: FollowUpKind;
        language?: string;
        angle?: FlowAngle;
        methodLevel?: boolean;
        followUp: string;
    }): Promise<FollowUpResult | {
        error: string;
    }>;
    /**
     * Cancel the in-flight follow-up redraw of the current workspace (the
     * panel's「取消」button while a redraw is running): aborting the stream
     * stops the LLM call and the cache is never overwritten — the old figure
     * stays in place.
     * @returns whether a follow-up generation was aborted.
     */
    remoteCancelFollowUp(): Promise<{
        ok: boolean;
    }>;
    /**
     * Abort every in-flight LLM generation for the current workspace (the
     *「⏹ 终止」button). The active AbortSignal fires, so provider streams stop
     * promptly; the client drops the pending responses locally.
     * @returns whether a generation was aborted.
     */
    remoteCancelGeneration(): Promise<{
        ok: boolean;
    }>;
    /**
     * Structured figure data for the interaction tab — READ ONLY: serve the
     * versioned structured cache; null when absent/stale. The shared-profile
     * fallback and LLM induction are WRITE-path only (「🤖 AI 生成」 /
     * regenerateFigure). Opening the panel or switching tabs never generates.
     * @param request - role language and method-level cache variant.
     * @returns event array, null, or an error.
     */
    remoteEvents(request: {
        language?: string;
        methodLevel?: boolean;
    }): Promise<Array<{
        event: string;
        mode: string;
        producers: string[];
        consumers: string[];
        note: string;
    }> | null | {
        error: string;
    }>;
    /**
     * Flow diagram — READ ONLY: serve the versioned cache; null when
     * absent/stale. Doc extraction, pseudo transcode, profile and LLM
     * induction are WRITE-path only (「🤖 AI 生成」 / regenerateFigure).
     * Opening the panel or switching tabs never generates.
     * @param request - role language, viewpoint, and method-level variant.
     * @returns the cached diagram, null, or an error.
     */
    remoteFlow(request: {
        language?: string;
        angle?: FlowAngle;
        methodLevel?: boolean;
    }): Promise<ArchLensFlowResult | null | {
        error: string;
    }>;
    /**
     * Code-derived insights: services/events/tools/remotes extracted from each
     * package's entry source. This is the "code-first" view — documentation is
     * a reference, but the analysis never depends on it.
     * @returns insight records or an error.
     */
    remoteAnalyze(): Promise<ArchLensCodeInsight[] | {
        error: string;
    }>;
    /**
     * AI one-line duty summaries for the package catalog. READ (default): serve
     * the persisted cache AS IS — possibly partial (generation batches stop at
     * the RPC budget). The catalog is a SCAN fact (每包的 README/description 兜底
     * 是 dutyText 的行级契约), so withholding the whole table over uncovered rows
     * turns "AI 覆盖了 80/247" into a永久空态: the incremental pass judges the
     * cache stamp-valid and never fills it, while a completeness-gated read never
     * serves it — the half-generated cache could neither grow nor be seen.
     * WRITE (force=true, the catalog「🤖 AI 生成」): generate the missing
     * summaries (LLM) and persist them (merges over the existing partial map).
     * @param request - output language (default 中文) and force flag.
     * @returns id → summary map (whatever is current), null when no cache exists
     *   at this facts version, or an error.
     */
    remoteSummarizeDuties(request: {
        language?: string;
        force?: boolean;
    }): Promise<Record<string, string> | null | {
        error: string;
    }>;
    /**
     * AI learning-progress summary: contrasts the note targets against the
     * scanned graph and appends a model-generated entry to the note file bottom.
     * @param request - role language and whether to force regeneration.
     * @returns progress stats plus the generated summary, or an error.
     */
    remoteProgress(request: {
        language?: string;
        force?: boolean;
    }): Promise<ArchLensProgressResult | {
        error: string;
    }>;
    /**
     * Read-only learning-progress statistics (no LLM call).
     * @returns asked/unasked lists and the coverage percentage.
     */
    remoteProgressStats(): Promise<{
        asked: string[];
        unasked: string[];
        total: number;
        progress: number;
    } | {
        error: string;
    }>;
    /**
     * LLM usage accounting: totals and the newest recorded calls (see
     * llm-stats.ts for the estimation rule). The snapshot is also persisted to
     * `index/.arch-lens-llm-stats.json` under the workspace so token spend is
     * inspectable outside the panel and survives restarts.
     * @returns the accounting snapshot.
     */
    remoteLlmStats(): Promise<LlmStatsSnapshot>;
    /**
     * Stage question metadata for the next assistant/message answer. Memory
     * only — the file write stays exclusively on the event path below.
     * An empty `text` CLEARS any staged metadata instead of staging: the desk
     * uses that after a failed explain send so no later ordinary
     * assistant/message gets mis-recorded as an explain (no extra wire name —
     * this stays within the official notePending contract).
     * @param request - target label, question text, and calling session id.
     * @returns acknowledgement.
     */
    remoteNotePending(request: {
        target: string;
        text: string;
        sessionId?: string;
    }): Promise<{
        ok: true;
    }>;
    /**
     * Read the persisted per-workspace prompt configuration.
     * @returns the config and its storage path.
     */
    remotePromptConfig(): Promise<ArchLensPromptConfigResult>;
    /**
     * Persist the per-workspace prompt configuration.
     * @param request - config fields to store (absent fields keep their stored value).
     * @returns the stored config and its path.
     */
    remotePromptConfigSave(request: ArchLensPromptConfig): Promise<ArchLensPromptConfigResult | {
        error: string;
    }>;
    /** Register the single note-write path: assistant/message events. */
    protected [Service.init](): Promise<void>;
    /** Policy-derived workspace root, used only when the event session has no cwd. */
    private rootFromPolicy;
}
export default ArchLensService;
//# sourceMappingURL=index.d.ts.map