packages:
  - packages/*
allowBuilds:
  tree-sitter: set this to true or false
  tree-sitter-java: set this to true or false
  tree-sitter-javascript: set this to true or false
  tree-sitter-python: set this to true or false
  tree-sitter-typescript: set this to true or false
onlyBuiltDependencies:
  - tree-sitter
  - tree-sitter-java
  - tree-sitter-javascript
  - tree-sitter-python
  - tree-sitter-typescript
