/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const ArchLensConceptNodeRemoteCodec$schema = z.object({
  'id': z.string(),
  'name': z.string(),
  'desc': z.string(),
  'inside': z.string().optional(),
  'pkg': z.string().optional(),
  'children': z.array(z.lazy(() => ArchLensConceptNodeRemoteCodec$schema)).optional(),
  'source': z.union([z.literal("flow"), z.literal("doc")]).optional(),
  'ref': z.string().optional(),
  'sourceText': z.string().optional(),
})
const ArchLensConceptNodeRemoteCodec$schema2 = z.object({
  'id': z.string(),
  'name': z.string(),
  'desc': z.string(),
  'inside': z.string().optional(),
  'pkg': z.string().optional(),
  'children': z.array(z.lazy(() => ArchLensConceptNodeRemoteCodec$schema2)).optional(),
  'source': z.union([z.literal("flow"), z.literal("doc")]).optional(),
  'ref': z.string().optional(),
  'sourceText': z.string().optional(),
})
const ArchLensConceptNodeRemoteCodec$schema3 = z.object({
  'id': z.string(),
  'name': z.string(),
  'desc': z.string(),
  'inside': z.string().optional(),
  'pkg': z.string().optional(),
  'children': z.array(z.lazy(() => ArchLensConceptNodeRemoteCodec$schema3)).optional(),
  'source': z.union([z.literal("flow"), z.literal("doc")]).optional(),
  'ref': z.string().optional(),
  'sourceText': z.string().optional(),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_analyze_result$schema = z.union([z.array(z.object({
  'id': z.string(),
  'provides': z.array(z.string()),
  'listens': z.array(z.string()),
  'tools': z.array(z.string()),
  'remotes': z.array(z.string()),
})), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_cancelGeneration_result$schema = z.object({
  'ok': z.boolean(),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_component_parameter_0$schema = z.object({
  'id': z.string(),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_component_result$schema = z.union([z.object({
  'id': z.string(),
  'short': z.string(),
  'group': z.string(),
  'blurb': z.string(),
  'files': z.array(z.object({
  'name': z.string(),
  'role': z.union([z.literal(""), z.literal("entry"), z.literal("types"), z.literal("invariant"), z.literal("assembly"), z.literal("test")]),
})),
  'deps': z.array(z.string()),
  'dependents': z.array(z.string()),
  'snippet': z.string(),
  'keyLines': z.array(z.string()),
}), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_conceptTree_parameter_0$schema = z.object({
  'language': z.string().optional(),
  'force': z.boolean().optional(),
  'methodLevel': z.boolean().optional(),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_conceptTree_result$schema = z.union([z.array(z.object({
  'id': z.string(),
  'name': z.string(),
  'desc': z.string(),
  'inside': z.string().optional(),
  'pkg': z.string().optional(),
  'children': z.array(z.lazy(() => ArchLensConceptNodeRemoteCodec$schema2)).optional(),
  'source': z.union([z.literal("flow"), z.literal("doc")]).optional(),
  'ref': z.string().optional(),
  'sourceText': z.string().optional(),
})), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_customFigure_parameter_0$schema = z.object({
  'figureId': z.string().optional(),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_customFigure_result$schema = z.union([z.literal(null), z.object({
  'figureId': z.string(),
  'title': z.string(),
  'diagram': z.string(),
  'summary': z.string(),
  'text': z.string(),
  'saved': z.boolean().optional(),
}), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_customFigureDelete_parameter_0$schema = z.object({
  'figureId': z.string(),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_customFigureDelete_result$schema = z.union([z.object({
  'ok': z.literal(true),
}), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_customFigureList_result$schema = z.union([z.array(z.object({
  'figureId': z.string(),
  'title': z.string(),
  'text': z.string(),
  'saved': z.boolean(),
  'savedAt': z.string().optional(),
})), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_customFigurePrompt_parameter_0$schema = z.object({
  'text': z.string(),
  'figureId': z.string().optional(),
  'language': z.string().optional(),
  'context': z.object({
  'blurbs': z.record(z.string(), z.string()).optional(),
}).optional(),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_customFigurePrompt_result$schema = z.union([z.object({
  'figId': z.string(),
  'figureId': z.string(),
  'prompt': z.string(),
}), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_dynamicFigure_parameter_0$schema = z.object({
  'kind': z.union([z.literal("seq-edge"), z.literal("flow-subgraph"), z.literal("overview")]),
  'targetKey': z.string(),
  'language': z.string().optional(),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_dynamicFigure_result$schema = z.union([z.literal(null), z.object({
  'title': z.string(),
  'diagram': z.string(),
  'kind': z.union([z.literal("seq-edge"), z.literal("flow-subgraph"), z.literal("overview")]),
  'targetKey': z.string(),
}), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_dynamicFigurePrompt_parameter_0$schema = z.object({
  'kind': z.union([z.literal("seq-edge"), z.literal("flow-subgraph"), z.literal("overview")]),
  'target': z.object({
  'from': z.string().optional(),
  'to': z.string().optional(),
  'label': z.string().optional(),
  'stage': z.string().optional(),
}),
  'language': z.string().optional(),
  'context': z.object({
  'mermaid': z.string().optional(),
  'blurbs': z.record(z.string(), z.string()).optional(),
}).optional(),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_dynamicFigurePrompt_result$schema = z.union([z.object({
  'figId': z.string(),
  'prompt': z.string(),
}), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_events_parameter_0$schema = z.object({
  'language': z.string().optional(),
  'methodLevel': z.boolean().optional(),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_events_result$schema = z.union([z.literal(null), z.array(z.object({
  'event': z.string(),
  'mode': z.string(),
  'producers': z.array(z.string()),
  'consumers': z.array(z.string()),
  'note': z.string(),
})), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_figureFollowUp_parameter_0$schema = z.object({
  'kind': z.union([z.literal("flow"), z.literal("concepts"), z.literal("seq"), z.literal("core"), z.literal("overview"), z.literal("events")]),
  'language': z.string().optional(),
  'angle': z.union([z.literal("event"), z.literal("pipeline")]).optional(),
  'methodLevel': z.boolean().optional(),
  'followUp': z.string(),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_figureFollowUp_result$schema = z.union([z.array(z.object({
  'id': z.string(),
  'name': z.string(),
  'desc': z.string(),
  'inside': z.string().optional(),
  'pkg': z.string().optional(),
  'children': z.array(z.lazy(() => ArchLensConceptNodeRemoteCodec$schema)).optional(),
  'source': z.union([z.literal("flow"), z.literal("doc")]).optional(),
  'ref': z.string().optional(),
  'sourceText': z.string().optional(),
})), z.object({
  'source': z.union([z.literal("flow"), z.literal("doc"), z.literal("code")]),
  'messages': z.array(z.object({
  'from': z.string(),
  'to': z.string(),
  'label': z.string(),
  'syms': z.array(z.string()).optional(),
  'file': z.string().optional(),
})),
  'nodes': z.array(z.object({
  'id': z.string(),
  'role': z.union([z.literal("entry"), z.literal("hub"), z.literal("leaf")]),
  'citedBy': z.number(),
  'cites': z.number(),
  'path': z.string(),
})).optional(),
  'ref': z.string().optional(),
}), z.object({
  'title': z.string(),
  'source': z.union([z.literal("flow"), z.literal("doc")]),
  'ref': z.string().optional(),
  'sourceText': z.string().optional(),
  'angle': z.union([z.literal("event"), z.literal("pipeline")]).optional(),
  'mermaid': z.string(),
}), z.array(z.object({
  'event': z.string(),
  'mode': z.string(),
  'producers': z.array(z.string()),
  'consumers': z.array(z.string()),
  'note': z.string(),
})), z.object({
  'kind': z.literal("flowchart"),
  'source': z.string(),
  'core': z.object({
  'ids': z.array(z.string()),
  'source': z.union([z.literal("flow"), z.literal("curated")]),
  'ref': z.string().optional(),
}),
}), z.object({
  'title': z.string(),
  'diagram': z.string(),
  'kind': z.literal("overview"),
  'targetKey': z.string(),
}), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_figurePrompt_parameter_0$schema = z.object({
  'kind': z.union([z.literal("flow"), z.literal("concepts"), z.literal("seq"), z.literal("interaction"), z.literal("deps"), z.literal("er")]),
  'language': z.string().optional(),
  'angle': z.union([z.literal("event"), z.literal("pipeline")]).optional(),
  'methodLevel': z.boolean().optional(),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_figurePrompt_result$schema = z.union([z.object({
  'figId': z.string(),
  'prompt': z.string(),
}), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_flow_parameter_0$schema = z.object({
  'language': z.string().optional(),
  'force': z.boolean().optional(),
  'angle': z.union([z.literal("event"), z.literal("pipeline")]).optional(),
  'methodLevel': z.boolean().optional(),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_flow_result$schema = z.union([z.object({
  'title': z.string(),
  'source': z.union([z.literal("flow"), z.literal("doc")]),
  'ref': z.string().optional(),
  'sourceText': z.string().optional(),
  'angle': z.union([z.literal("event"), z.literal("pipeline")]).optional(),
  'mermaid': z.string(),
}), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_generateDocs_parameter_0$schema = z.object({
  'language': z.string().optional(),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_generateDocs_result$schema = z.union([z.object({
  'path': z.string(),
}), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_generateDocSection_parameter_0$schema = z.object({
  'kind': z.union([z.literal("concepts"), z.literal("seq"), z.literal("interaction"), z.literal("deps"), z.literal("er"), z.literal("catalog")]),
  'language': z.string().optional(),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_generateDocSection_result$schema = z.union([z.object({
  'path': z.string(),
}), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_generationStatus_result$schema = z.union([z.literal(null), z.object({
  'active': z.boolean(),
  'stage': z.string(),
  'elapsedMs': z.number(),
  'outputChars': z.number(),
  'preview': z.string(),
  'seq': z.number(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_generationStatusNext_parameter_0$schema = z.object({
  'since': z.number().optional(),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_generationStatusNext_result$schema = z.union([z.literal(null), z.object({
  'status': z.object({
  'active': z.boolean(),
  'stage': z.string(),
  'elapsedMs': z.number(),
  'outputChars': z.number(),
  'preview': z.string(),
  'seq': z.number(),
}),
  'seq': z.number(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_graph_result$schema = z.union([z.object({
  'root': z.string(),
  'groups': z.array(z.string()),
  'nodes': z.array(z.object({
  'id': z.string(),
  'short': z.string(),
  'group': z.string(),
  'blurb': z.string(),
  'blurbZh': z.string().optional(),
  'files': z.array(z.string()),
  'deps': z.array(z.string()),
  'path': z.string(),
  'detail': z.object({
  'id': z.string(),
  'short': z.string(),
  'group': z.string(),
  'blurb': z.string(),
  'files': z.array(z.object({
  'name': z.string(),
  'role': z.union([z.literal(""), z.literal("entry"), z.literal("types"), z.literal("invariant"), z.literal("assembly"), z.literal("test")]),
})),
  'deps': z.array(z.string()),
  'dependents': z.array(z.string()),
  'snippet': z.string(),
  'keyLines': z.array(z.string()),
}),
})),
  'edges': z.array(z.object({
  'from': z.string(),
  'to': z.string(),
})),
}), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_lastAnswer_parameter_0$schema = z.object({
  'sessionId': z.string().optional(),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_lastAnswer_result$schema = z.union([z.object({
  'text': z.string(),
  'reasoning': z.string(),
}), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_llmStats_result$schema = z.object({
  'totalCalls': z.number(),
  'totalInTokens': z.number(),
  'totalOutTokens': z.number(),
  'totalUsageInTokens': z.number(),
  'totalUsageOutTokens': z.number(),
  'totalMs': z.number(),
  'records': z.array(z.object({
  'kind': z.string(),
  'at': z.number(),
  'inChars': z.number(),
  'outChars': z.number(),
  'estInTokens': z.number(),
  'estOutTokens': z.number(),
  'usage': z.object({
  'inTokens': z.number(),
  'outTokens': z.number(),
  'cacheReadTokens': z.number().optional(),
  'cacheWriteTokens': z.number().optional(),
  'reasoningTokens': z.number().optional(),
}).optional(),
  'ms': z.number(),
})),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_mermaidCore_parameter_0$schema = z.object({
  'kind': z.union([z.literal("flowchart"), z.literal("erDiagram")]),
  'language': z.string().optional(),
  'force': z.boolean().optional(),
  'methodLevel': z.boolean().optional(),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_mermaidCore_result$schema = z.union([z.object({
  'kind': z.union([z.literal("flowchart"), z.literal("erDiagram")]),
  'source': z.string(),
  'core': z.object({
  'ids': z.array(z.string()),
  'source': z.union([z.literal("flow"), z.literal("curated")]),
  'ref': z.string().optional(),
}),
}), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_mermaidDeps_result$schema = z.union([z.object({
  'kind': z.literal("flowchart"),
  'source': z.string(),
}), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_mermaidEr_result$schema = z.union([z.object({
  'kind': z.literal("erDiagram"),
  'source': z.string(),
}), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_mermaidIndexed_parameter_0$schema = z.object({
  'kind': z.union([z.literal("flowchart"), z.literal("erDiagram")]),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_mermaidIndexed_result$schema = z.union([z.object({
  'kind': z.union([z.literal("flowchart"), z.literal("erDiagram")]),
  'source': z.string(),
}), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_notePending_parameter_0$schema = z.object({
  'target': z.string(),
  'text': z.string(),
  'sessionId': z.string().optional(),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_notePending_result$schema = z.object({
  'ok': z.literal(true),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_notes_result$schema = z.union([z.object({
  'path': z.string(),
  'entries': z.array(z.object({
  'time': z.string(),
  'target': z.string(),
  'preview': z.string(),
})),
}), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_overviewFigure_parameter_0$schema = z.object({
  'language': z.string().optional(),
  'force': z.boolean().optional(),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_overviewFigure_result$schema = z.union([z.object({
  'title': z.string(),
  'mermaid': z.string(),
  'core': z.object({
  'ids': z.array(z.string()),
  'source': z.union([z.literal("flow"), z.literal("curated")]),
  'ref': z.string().optional(),
}),
}), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_progress_parameter_0$schema = z.object({
  'language': z.string().optional(),
  'force': z.boolean().optional(),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_progress_result$schema = z.union([z.object({
  'path': z.string(),
  'summary': z.string(),
  'asked': z.array(z.string()),
  'unasked': z.array(z.string()),
  'total': z.number(),
  'progress': z.number(),
}), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_progressStats_result$schema = z.union([z.object({
  'asked': z.array(z.string()),
  'unasked': z.array(z.string()),
  'total': z.number(),
  'progress': z.number(),
}), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_promptConfig_result$schema = z.object({
  'path': z.string(),
  'config': z.object({
  'overviewPrompt': z.string().optional(),
  'explainStyle': z.string().optional(),
  'language': z.string().optional(),
  'useDefaults': z.boolean().optional(),
}),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_promptConfigSave_parameter_0$schema = z.object({
  'overviewPrompt': z.string().optional(),
  'explainStyle': z.string().optional(),
  'language': z.string().optional(),
  'useDefaults': z.boolean().optional(),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_promptConfigSave_result$schema = z.union([z.object({
  'path': z.string(),
  'config': z.object({
  'overviewPrompt': z.string().optional(),
  'explainStyle': z.string().optional(),
  'language': z.string().optional(),
  'useDefaults': z.boolean().optional(),
}),
}), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_refresh_result$schema = z.union([z.object({
  'root': z.string(),
  'groups': z.array(z.string()),
  'nodes': z.array(z.object({
  'id': z.string(),
  'short': z.string(),
  'group': z.string(),
  'blurb': z.string(),
  'blurbZh': z.string().optional(),
  'files': z.array(z.string()),
  'deps': z.array(z.string()),
  'path': z.string(),
  'detail': z.object({
  'id': z.string(),
  'short': z.string(),
  'group': z.string(),
  'blurb': z.string(),
  'files': z.array(z.object({
  'name': z.string(),
  'role': z.union([z.literal(""), z.literal("entry"), z.literal("types"), z.literal("invariant"), z.literal("assembly"), z.literal("test")]),
})),
  'deps': z.array(z.string()),
  'dependents': z.array(z.string()),
  'snippet': z.string(),
  'keyLines': z.array(z.string()),
}),
})),
  'edges': z.array(z.object({
  'from': z.string(),
  'to': z.string(),
})),
}), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_refreshIndex_result$schema = z.object({
  'ok': z.literal(true),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_regenerateFigure_parameter_0$schema = z.object({
  'kind': z.union([z.literal("flow"), z.literal("concepts"), z.literal("seq"), z.literal("interaction"), z.literal("deps"), z.literal("er")]),
  'language': z.string().optional(),
  'methodLevel': z.boolean().optional(),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_regenerateFigure_result$schema = z.union([z.object({
  'kind': z.literal("concepts"),
  'tree': z.array(z.object({
  'id': z.string(),
  'name': z.string(),
  'desc': z.string(),
  'inside': z.string().optional(),
  'pkg': z.string().optional(),
  'children': z.array(z.lazy(() => ArchLensConceptNodeRemoteCodec$schema3)).optional(),
  'source': z.union([z.literal("flow"), z.literal("doc")]).optional(),
  'ref': z.string().optional(),
  'sourceText': z.string().optional(),
})),
}), z.object({
  'kind': z.literal("seq"),
  'messages': z.array(z.object({
  'from': z.string(),
  'to': z.string(),
  'label': z.string(),
  'syms': z.array(z.string()).optional(),
  'file': z.string().optional(),
})),
}), z.object({
  'kind': z.literal("flow"),
  'flows': z.object({
  'event': z.object({
  'title': z.string(),
  'source': z.union([z.literal("flow"), z.literal("doc")]),
  'ref': z.string().optional(),
  'sourceText': z.string().optional(),
  'angle': z.union([z.literal("event"), z.literal("pipeline")]).optional(),
  'mermaid': z.string(),
}).optional(),
  'pipeline': z.object({
  'title': z.string(),
  'source': z.union([z.literal("flow"), z.literal("doc")]),
  'ref': z.string().optional(),
  'sourceText': z.string().optional(),
  'angle': z.union([z.literal("event"), z.literal("pipeline")]).optional(),
  'mermaid': z.string(),
}).optional(),
}),
}), z.object({
  'kind': z.literal("interaction"),
  'events': z.array(z.object({
  'event': z.string(),
  'mode': z.string(),
  'producers': z.array(z.string()),
  'consumers': z.array(z.string()),
  'note': z.string(),
})),
}), z.object({
  'kind': z.literal("core"),
  'core': z.object({
  'ids': z.array(z.string()),
  'source': z.union([z.literal("flow"), z.literal("curated")]),
  'ref': z.string().optional(),
}),
}), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_saveCustomFigure_parameter_0$schema = z.object({
  'figureId': z.string(),
  'language': z.string().optional(),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_saveCustomFigure_result$schema = z.union([z.object({
  'ok': z.literal(true),
  'path': z.string(),
}), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_sequence_parameter_0$schema = z.object({
  'language': z.string().optional(),
  'prefer': z.union([z.literal("flow"), z.literal("code")]).optional(),
  'methodLevel': z.boolean().optional(),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_sequence_result$schema = z.union([z.literal(null), z.object({
  'source': z.union([z.literal("flow"), z.literal("doc"), z.literal("code")]),
  'messages': z.array(z.object({
  'from': z.string(),
  'to': z.string(),
  'label': z.string(),
  'syms': z.array(z.string()).optional(),
  'file': z.string().optional(),
})),
  'nodes': z.array(z.object({
  'id': z.string(),
  'role': z.union([z.literal("entry"), z.literal("hub"), z.literal("leaf")]),
  'citedBy': z.number(),
  'cites': z.number(),
  'path': z.string(),
})).optional(),
  'ref': z.string().optional(),
}), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_setSession_parameter_0$schema = z.union([z.literal(null), z.string()])
const _deepseek_ai_dsh_arch_lens_backend_archLens_setSession_result$schema = z.object({
  'ok': z.literal(true),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_summarizeDuties_parameter_0$schema = z.object({
  'language': z.string().optional(),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_summarizeDuties_result$schema = z.union([z.record(z.string(), z.string()), z.object({
  'error': z.string(),
})])

export const TYPERT = {
  package: '@deepseek-ai/dsh-arch-lens-backend',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/analyze',
      service: 'archLens',
      namespace: 'archLens',
      method: 'analyze',
      implementation: 'remoteAnalyze',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/analyze:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_analyze_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":1312,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/cancelGeneration',
      service: 'archLens',
      namespace: 'archLens',
      method: 'cancelGeneration',
      implementation: 'remoteCancelGeneration',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/cancelGeneration:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_cancelGeneration_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":1244,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/component',
      service: 'archLens',
      namespace: 'archLens',
      method: 'component',
      implementation: 'remoteComponent',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/component:request',
            schema: _deepseek_ai_dsh_arch_lens_backend_archLens_component_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/component:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_component_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":361,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/conceptTree',
      service: 'archLens',
      namespace: 'archLens',
      method: 'conceptTree',
      implementation: 'remoteConceptTree',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/conceptTree:request',
            schema: _deepseek_ai_dsh_arch_lens_backend_archLens_conceptTree_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/conceptTree:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_conceptTree_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":506,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/customFigure',
      service: 'archLens',
      namespace: 'archLens',
      method: 'customFigure',
      implementation: 'remoteCustomFigure',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/customFigure:request',
            schema: _deepseek_ai_dsh_arch_lens_backend_archLens_customFigure_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/customFigure:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_customFigure_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":982,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/customFigureDelete',
      service: 'archLens',
      namespace: 'archLens',
      method: 'customFigureDelete',
      implementation: 'remoteCustomFigureDelete',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/customFigureDelete:request',
            schema: _deepseek_ai_dsh_arch_lens_backend_archLens_customFigureDelete_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/customFigureDelete:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_customFigureDelete_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":1186,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/customFigureList',
      service: 'archLens',
      namespace: 'archLens',
      method: 'customFigureList',
      implementation: 'remoteCustomFigureList',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/customFigureList:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_customFigureList_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":1107,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/customFigurePrompt',
      service: 'archLens',
      namespace: 'archLens',
      method: 'customFigurePrompt',
      implementation: 'remoteCustomFigurePrompt',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/customFigurePrompt:request',
            schema: _deepseek_ai_dsh_arch_lens_backend_archLens_customFigurePrompt_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/customFigurePrompt:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_customFigurePrompt_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":938,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/dynamicFigure',
      service: 'archLens',
      namespace: 'archLens',
      method: 'dynamicFigure',
      implementation: 'remoteDynamicFigure',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/dynamicFigure:request',
            schema: _deepseek_ai_dsh_arch_lens_backend_archLens_dynamicFigure_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/dynamicFigure:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_dynamicFigure_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":908,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/dynamicFigurePrompt',
      service: 'archLens',
      namespace: 'archLens',
      method: 'dynamicFigurePrompt',
      implementation: 'remoteDynamicFigurePrompt',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/dynamicFigurePrompt:request',
            schema: _deepseek_ai_dsh_arch_lens_backend_archLens_dynamicFigurePrompt_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/dynamicFigurePrompt:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_dynamicFigurePrompt_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":842,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/events',
      service: 'archLens',
      namespace: 'archLens',
      method: 'events',
      implementation: 'remoteEvents',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/events:request',
            schema: _deepseek_ai_dsh_arch_lens_backend_archLens_events_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/events:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_events_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":1256,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/figureFollowUp',
      service: 'archLens',
      namespace: 'archLens',
      method: 'figureFollowUp',
      implementation: 'remoteFigureFollowUp',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/figureFollowUp:request',
            schema: _deepseek_ai_dsh_arch_lens_backend_archLens_figureFollowUp_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/figureFollowUp:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_figureFollowUp_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":1223,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/figurePrompt',
      service: 'archLens',
      namespace: 'archLens',
      method: 'figurePrompt',
      implementation: 'remoteFigurePrompt',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/figurePrompt:request',
            schema: _deepseek_ai_dsh_arch_lens_backend_archLens_figurePrompt_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/figurePrompt:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_figurePrompt_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":785,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/flow',
      service: 'archLens',
      namespace: 'archLens',
      method: 'flow',
      implementation: 'remoteFlow',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/flow:request',
            schema: _deepseek_ai_dsh_arch_lens_backend_archLens_flow_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/flow:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_flow_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":1292,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/generateDocs',
      service: 'archLens',
      namespace: 'archLens',
      method: 'generateDocs',
      implementation: 'remoteGenerateDocs',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/generateDocs:request',
            schema: _deepseek_ai_dsh_arch_lens_backend_archLens_generateDocs_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/generateDocs:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_generateDocs_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":528,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/generateDocSection',
      service: 'archLens',
      namespace: 'archLens',
      method: 'generateDocSection',
      implementation: 'remoteGenerateDocSection',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/generateDocSection:request',
            schema: _deepseek_ai_dsh_arch_lens_backend_archLens_generateDocSection_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/generateDocSection:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_generateDocSection_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":548,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/generationStatus',
      service: 'archLens',
      namespace: 'archLens',
      method: 'generationStatus',
      implementation: 'remoteGenerationStatus',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/generationStatus:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_generationStatus_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":752,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/generationStatusNext',
      service: 'archLens',
      namespace: 'archLens',
      method: 'generationStatusNext',
      implementation: 'remoteGenerationStatusNext',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/generationStatusNext:request',
            schema: _deepseek_ai_dsh_arch_lens_backend_archLens_generationStatusNext_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/generationStatusNext:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_generationStatusNext_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":768,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/graph',
      service: 'archLens',
      namespace: 'archLens',
      method: 'graph',
      implementation: 'remoteGraph',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/graph:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_graph_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":251,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/lastAnswer',
      service: 'archLens',
      namespace: 'archLens',
      method: 'lastAnswer',
      implementation: 'remoteLastAnswer',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/lastAnswer:request',
            schema: _deepseek_ai_dsh_arch_lens_backend_archLens_lastAnswer_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/lastAnswer:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_lastAnswer_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":720,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/llmStats',
      service: 'archLens',
      namespace: 'archLens',
      method: 'llmStats',
      implementation: 'remoteLlmStats',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend/types#LlmStatsSnapshot',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_llmStats_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":1368,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/mermaidCore',
      service: 'archLens',
      namespace: 'archLens',
      method: 'mermaidCore',
      implementation: 'remoteMermaidCore',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/mermaidCore:request',
            schema: _deepseek_ai_dsh_arch_lens_backend_archLens_mermaidCore_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/mermaidCore:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_mermaidCore_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":436,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/mermaidDeps',
      service: 'archLens',
      namespace: 'archLens',
      method: 'mermaidDeps',
      implementation: 'remoteMermaidDeps',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/mermaidDeps:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_mermaidDeps_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":385,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/mermaidEr',
      service: 'archLens',
      namespace: 'archLens',
      method: 'mermaidEr',
      implementation: 'remoteMermaidEr',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/mermaidEr:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_mermaidEr_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":396,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/mermaidIndexed',
      service: 'archLens',
      namespace: 'archLens',
      method: 'mermaidIndexed',
      implementation: 'remoteMermaidIndexed',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/mermaidIndexed:request',
            schema: _deepseek_ai_dsh_arch_lens_backend_archLens_mermaidIndexed_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/mermaidIndexed:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_mermaidIndexed_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":410,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/notePending',
      service: 'archLens',
      namespace: 'archLens',
      method: 'notePending',
      implementation: 'remoteNotePending',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/notePending:request',
            schema: _deepseek_ai_dsh_arch_lens_backend_archLens_notePending_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/notePending:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_notePending_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":1393,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/notes',
      service: 'archLens',
      namespace: 'archLens',
      method: 'notes',
      implementation: 'remoteNotes',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/notes:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_notes_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":374,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/overviewFigure',
      service: 'archLens',
      namespace: 'archLens',
      method: 'overviewFigure',
      implementation: 'remoteOverviewFigure',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/overviewFigure:request',
            schema: _deepseek_ai_dsh_arch_lens_backend_archLens_overviewFigure_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/overviewFigure:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_overviewFigure_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":462,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/progress',
      service: 'archLens',
      namespace: 'archLens',
      method: 'progress',
      implementation: 'remoteProgress',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/progress:request',
            schema: _deepseek_ai_dsh_arch_lens_backend_archLens_progress_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/progress:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_progress_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":1339,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/progressStats',
      service: 'archLens',
      namespace: 'archLens',
      method: 'progressStats',
      implementation: 'remoteProgressStats',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/progressStats:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_progressStats_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":1352,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/promptConfig',
      service: 'archLens',
      namespace: 'archLens',
      method: 'promptConfig',
      implementation: 'remotePromptConfig',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend/types#ArchLensPromptConfigResult',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_promptConfig_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":1415,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/promptConfigSave',
      service: 'archLens',
      namespace: 'archLens',
      method: 'promptConfigSave',
      implementation: 'remotePromptConfigSave',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-arch-lens-backend/types#ArchLensPromptConfig',
            schema: _deepseek_ai_dsh_arch_lens_backend_archLens_promptConfigSave_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/promptConfigSave:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_promptConfigSave_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":1436,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/refresh',
      service: 'archLens',
      namespace: 'archLens',
      method: 'refresh',
      implementation: 'remoteRefresh',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/refresh:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_refresh_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":263,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/refreshIndex',
      service: 'archLens',
      namespace: 'archLens',
      method: 'refreshIndex',
      implementation: 'remoteRefreshIndex',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/refreshIndex:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_refreshIndex_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":288,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/regenerateFigure',
      service: 'archLens',
      namespace: 'archLens',
      method: 'regenerateFigure',
      implementation: 'remoteRegenerateFigure',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/regenerateFigure:request',
            schema: _deepseek_ai_dsh_arch_lens_backend_archLens_regenerateFigure_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/regenerateFigure:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_regenerateFigure_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":598,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/saveCustomFigure',
      service: 'archLens',
      namespace: 'archLens',
      method: 'saveCustomFigure',
      implementation: 'remoteSaveCustomFigure',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/saveCustomFigure:request',
            schema: _deepseek_ai_dsh_arch_lens_backend_archLens_saveCustomFigure_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/saveCustomFigure:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_saveCustomFigure_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":1147,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/sequence',
      service: 'archLens',
      namespace: 'archLens',
      method: 'sequence',
      implementation: 'remoteSequence',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/sequence:request',
            schema: _deepseek_ai_dsh_arch_lens_backend_archLens_sequence_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/sequence:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_sequence_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":573,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/setSession',
      service: 'archLens',
      namespace: 'archLens',
      method: 'setSession',
      implementation: 'remoteSetSession',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'sessionId',
          wire: 'sessionId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/setSession:sessionId',
            schema: _deepseek_ai_dsh_arch_lens_backend_archLens_setSession_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/setSession:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_setSession_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":306,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/summarizeDuties',
      service: 'archLens',
      namespace: 'archLens',
      method: 'summarizeDuties',
      implementation: 'remoteSummarizeDuties',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/summarizeDuties:request',
            schema: _deepseek_ai_dsh_arch_lens_backend_archLens_summarizeDuties_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/summarizeDuties:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_summarizeDuties_result$schema,
      },
      sourceLocation: {"file":"packages/arch-lens-backend/src/index.ts","line":1324,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "The Arch Lens backend Remote service (`ctx.archLens`).",
        "summary": "The Arch Lens backend Remote service (`ctx.archLens`).",
        "tags": [],
        "jsDoc": "/**\n * The Arch Lens backend Remote service (`ctx.archLens`).\n */",
        "key": "archLens",
        "exportName": "ArchLensService",
        "members": [
          {
            "kind": "method",
            "name": "remoteGraph",
            "signature": "@Remote('graph') async remoteGraph(): Promise<ArchLensGraph | { error: string }>",
            "summary": "The scanned workspace graph (cached until refresh).",
            "jsDoc": "/**\n * The scanned workspace graph (cached until refresh).\n * @returns graph or error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteRefresh",
            "signature": "@Remote('refresh') async remoteRefresh(): Promise<ArchLensGraph | { error: string }>",
            "summary": "Rescan = REBUILD EVERY fact source: invalidate the scan graph, the code-index (in-memory + disk), and the AI caches (concept tree / sequence / events).",
            "jsDoc": "/**\n * Rescan = REBUILD EVERY fact source: invalidate the scan graph, the\n * code-index (in-memory + disk), and the AI caches (concept tree /\n * sequence / events). The next read of any figure re-derives from current\n * code and docs — no stale fact may survive a rescan.\n * @returns the fresh scan graph or error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteRefreshIndex",
            "signature": "@Remote('refreshIndex') async remoteRefreshIndex(): Promise<{ ok: true }>",
            "summary": "Refresh only the code-index facts (in-memory + disk invalidated).",
            "jsDoc": "/**\n * Refresh only the code-index facts (in-memory + disk invalidated). Used by\n * \"refresh this figure\": the figure then re-derives from a fresh index.\n * @returns acknowledgement.\n */"
          },
          {
            "kind": "method",
            "name": "remoteSetSession",
            "signature": "@Remote('setSession') async remoteSetSession(sessionId: string | null): Promise<{ ok: true }>",
            "summary": "Point the desk's data source at one session's workspace.",
            "jsDoc": "/**\n * Point the desk's data source at one session's workspace. This is the\n * official wire name (kept for harness-contract compatibility) but its\n * SEMANTICS are \"load, never invalidate\": only the target session id is\n * set and no cache is touched. The scan cache is keyed by workspace root,\n * so re-loading the same workspace (reopening the panel, switching between\n * its sessions) is instant, while a different workspace rescans\n * automatically on the next graph() call. Explicit invalidation stays\n * exclusively on refresh().\n * @param sessionId - target session id, or null for the policy root.\n * @returns acknowledgement.\n */"
          },
          {
            "kind": "method",
            "name": "remoteComponent",
            "signature": "@Remote('component') async remoteComponent(request: { id: string }): Promise<ArchLensComponentDetail | { error: string }>",
            "summary": "Detail projection for one package.",
            "jsDoc": "/**\n * Detail projection for one package. The graph carries precomputed details,\n * so this is a plain lookup (kept as a Remote for compatibility).\n * @param request - package id.\n * @returns detail or error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteNotes",
            "signature": "@Remote('notes') async remoteNotes(): Promise<ArchLensNotesResult | { error: string }>",
            "summary": "The note file listing, newest first.",
            "jsDoc": "/**\n * The note file listing, newest first.\n * @returns notes listing or an error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteMermaidDeps",
            "signature": "@Remote('mermaidDeps') async remoteMermaidDeps(): Promise<{ kind: 'flowchart'; source: string } | { error: string }>",
            "summary": "Mermaid dependency flowchart for the scanned graph.",
            "jsDoc": "/**\n * Mermaid dependency flowchart for the scanned graph.\n * @returns flowchart source or an error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteMermaidEr",
            "signature": "@Remote('mermaidEr') async remoteMermaidEr(): Promise<{ kind: 'erDiagram'; source: string } | { error: string }>",
            "summary": "Mermaid ER diagram of package relationships for the scanned graph.",
            "jsDoc": "/**\n * Mermaid ER diagram of package relationships for the scanned graph.\n * @returns erDiagram source or an error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteMermaidIndexed",
            "signature": "@Remote('mermaidIndexed') async remoteMermaidIndexed(request: { kind: 'flowchart' | 'erDiagram' }): Promise<{ kind: 'flowchart' | 'erDiagram'; source: string } | { error: string }>",
            "summary": "Mermaid diagrams over the code-index imports: source-level dependency edges (real imports) instead of npm peerDependencies.",
            "jsDoc": "/**\n * Mermaid diagrams over the code-index imports: source-level dependency\n * edges (real imports) instead of npm peerDependencies. Falls back to the\n * scanned-graph variants when the codeIndex service or a language is absent.\n * @param request - diagram kind.\n * @returns mermaid source or an error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteMermaidCore",
            "signature": "@Remote('mermaidCore') async remoteMermaidCore(request: { kind: 'flowchart' | 'erDiagram'; language?: string; force?: boolean; methodLevel?: boolean }): Promise<{ kind: 'flowchart' | 'erDiagram'; source: string; core: ArchLensCoreGraph } | { error: string }>",
            "summary": "Core-flow diagram (deps/ER overview): the LLM-selected core packages with rule-derived source-import edges.",
            "jsDoc": "/**\n * Core-flow diagram (deps/ER overview): the LLM-selected core packages with\n * rule-derived source-import edges. Returns the mermaid source plus the\n * selection provenance so the client can badge/explain it.\n * @param request - diagram kind, role language, and whether to force a new selection.\n * @returns mermaid source and core selection, or an error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteOverviewFigure",
            "signature": "@Remote('overviewFigure') async remoteOverviewFigure(request: { language?: string; force?: boolean }): Promise<{ title: string; mermaid: string; core: ArchLensCoreGraph } | { error: string }>",
            "summary": "架构概览 (rule-built): the core packages with their one-line duty under the name + source-level import edges between them — zero LLM, built from structured facts (core selection + graph blurbs + index imports).",
            "jsDoc": "/**\n * 架构概览 (rule-built): the core packages with their one-line duty under\n * the name + source-level import edges between them — zero LLM, built from\n * structured facts (core selection + graph blurbs + index imports). The\n * pure-LLM variant (dynamic figure kind 'overview') stays available for\n * comparison.\n * @param request - role language, force a new core selection.\n * @returns the overview mermaid + core selection, or an error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteConceptTree",
            "signature": "@Remote('conceptTree') async remoteConceptTree(request: { language?: string; force?: boolean; methodLevel?: boolean }): Promise<ArchLensConceptNode[] | { error: string }>",
            "summary": "Concept hierarchy via the one-way chain: architecture doc (extract + LLM enhance) first, LLM-from-flow as fallback.",
            "jsDoc": "/**\n * Concept hierarchy via the one-way chain: architecture doc (extract +\n * LLM enhance) first, LLM-from-flow as fallback. Cached per language.\n * @param request - role language and whether to force regeneration.\n * @returns concept-tree nodes or an error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteGenerateDocs",
            "signature": "@Remote('generateDocs') async remoteGenerateDocs(request: { language?: string }): Promise<{ path: string } | { error: string }>",
            "summary": "Generate the complete architecture doc (global button): one LLM pass writes concept/sequence/interaction/dependency/ER/catalog sections.",
            "jsDoc": "/**\n * Generate the complete architecture doc (global button): one LLM pass\n * writes concept/sequence/interaction/dependency/ER/catalog sections.\n * @param request - role language.\n * @returns the doc path or an error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteGenerateDocSection",
            "signature": "@Remote('generateDocSection') async remoteGenerateDocSection(request: { kind: 'concepts' | 'seq' | 'interaction' | 'deps' | 'er' | 'catalog'; language?: string }): Promise<{ path: string } | { error: string }>",
            "summary": "Generate one doc section on demand (per-tab \"AI generate\").",
            "jsDoc": "/**\n * Generate one doc section on demand (per-tab \"AI generate\"). Sequence and\n * interaction also refresh their structured caches.\n * @param request - section kind and role language.\n * @returns the doc path or an error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteSequence",
            "signature": "@Remote('sequence') async remoteSequence(request: { language?: string; prefer?: 'code' | 'flow'; methodLevel?: boolean }): Promise<ArchLensSequenceResult | null | { error: string }>",
            "summary": "Structured figure data for the sequence tab, resolved through the chain: real static call graph first (source 'code'), then the cached doc/LLM result, then the doc's sequence section (source 'doc'), then LLM induction (source 'flow').",
            "jsDoc": "/**\n * Structured figure data for the sequence tab, resolved through the chain:\n * real static call graph first (source 'code'), then the cached doc/LLM\n * result, then the doc's sequence section (source 'doc'), then LLM\n * induction (source 'flow'). With prefer 'flow' the static call-graph\n * stage is skipped, so the main-flow sequence view resolves from the\n * cache, the doc section, or LLM induction. The client renders an empty\n * state on null.\n * @param request - role language and preferred view ('code' | 'flow').\n * @returns the figure (with provenance), null, or an error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteRegenerateFigure",
            "signature": "@Remote('regenerateFigure') async remoteRegenerateFigure(request: { kind: 'concepts' | 'seq' | 'flow' | 'interaction' | 'deps' | 'er'; language?: string; methodLevel?: boolean }): Promise<RegenerateFigureResult | { error: string }>",
            "summary": "Per-tab \"AI generate\" (分离方案): regenerate ONE shared-profile field with one trimmed-summary LLM call and return the fresh figure data.",
            "jsDoc": "/**\n * Per-tab \"AI generate\" (分离方案): regenerate ONE shared-profile field\n * with one trimmed-summary LLM call and return the fresh figure data. The\n * profile is updated in memory and on disk; other figures are untouched\n * (except core regeneration, which invalidates flow/seq/events — see\n * analysis.ts). The client renders the returned data directly, so a\n * per-tab generate never rewrites docs/architecture.generated.md.\n * @param request - figure kind and role language.\n * @returns the regenerated field, or an error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteLastAnswer",
            "signature": "@Remote('lastAnswer') async remoteLastAnswer(request: { sessionId?: string }): Promise<{ text: string; reasoning: string } | { error: string }>",
            "summary": "The latest assistant answer of the target session: visible text plus the reasoning chain (thinking blocks).",
            "jsDoc": "/**\n * The latest assistant answer of the target session: visible text plus the\n * reasoning chain (thinking blocks). The panel shows the model's thinking\n * for the last explanation — the reasoning stays in the session message\n * (host-side projection), the client only renders a copy.\n * @param request - optional session id (defaults to the target session).\n * @returns the last assistant message's text/reasoning, or an error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteGenerationStatus",
            "signature": "@Remote('generationStatus') async remoteGenerationStatus(): Promise<GenerationStatus | null>",
            "summary": "Live generation status of the workspace (⚙️ 生成过程 box): what the LLM is currently doing — stage label, elapsed time, streamed output preview (reasoning tail while thinking).",
            "jsDoc": "/**\n * Live generation status of the workspace (⚙️ 生成过程 box): what the LLM\n * is currently doing — stage label, elapsed time, streamed output preview\n * (reasoning tail while thinking). Polled by the panel while a generation\n * is suspected in flight; null when nothing was generated yet.\n * @returns the live status, or null.\n */"
          },
          {
            "kind": "method",
            "name": "remoteGenerationStatusNext",
            "signature": "@Remote('generationStatusNext') async remoteGenerationStatusNext(request: { since?: number }): Promise<{ status: GenerationStatus; seq: number } | null>",
            "summary": "LONG-POLL push of the live generation status: resolves when the status seq differs from `since` (a change just happened — throttled to a smooth cadence), or after ~20s with the current snapshot (the panel re-issues immediately).",
            "jsDoc": "/**\n * LONG-POLL push of the live generation status: resolves when the status\n * seq differs from `since` (a change just happened — throttled to a smooth\n * cadence), or after ~20s with the current snapshot (the panel re-issues\n * immediately). One in-flight request at a time delivers the generation\n * process with SSE-like latency over the regular RPC channel.\n * @param request - the client's last seen seq.\n * @returns the current status snapshot, or null when nothing was generated.\n */"
          },
          {
            "kind": "method",
            "name": "remoteFigurePrompt",
            "signature": "@Remote('figurePrompt') async remoteFigurePrompt(request: { kind: 'concepts' | 'seq' | 'flow' | 'interaction' | 'deps' | 'er' language?: string angle?: FlowAngle methodLevel?: boolean }): Promise<{ figId: string; prompt: string } | { error: string }>",
            "summary": "Build the session message that asks the agent to produce ONE figure (「图生成走会话」): the prompt embeds the code facts; the CLIENT sends it into the current session, so the GUI's own conversation stream shows the agent working in real time.",
            "jsDoc": "/**\n * Build the session message that asks the agent to produce ONE figure\n * (「图生成走会话」): the prompt embeds the code facts; the CLIENT sends it\n * into the current session, so the GUI's own conversation stream shows the\n * agent working in real time. This RPC stages a pendingFigure (matched by\n * figId) and returns immediately — the figure lands in the cache when the\n * agent answers, and the panel refetches it after the turn completes.\n * @param request - figure kind, role language, flow angle, 🔬 method level.\n * @returns the figId + prompt to send, or an error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteDynamicFigurePrompt",
            "signature": "@Remote('dynamicFigurePrompt') async remoteDynamicFigurePrompt(request: { kind: 'seq-edge' | 'flow-subgraph' | 'overview' target: { from?: string; to?: string; label?: string; stage?: string } language?: string context?: { mermaid?: string; blurbs?: Record<string, string> } }): Promise<{ figId: string; prompt: string } | { error: string }>",
            "summary": "Build the session message that asks the agent to draw ONE DYNAMIC detail figure (「动态画图」hover drill-down): a sequence-edge drill-down (the two packages' method-level call sequence) or a flow-subgraph expansion (that stage as a detailed flowchart).",
            "jsDoc": "/**\n * Build the session message that asks the agent to draw ONE DYNAMIC detail\n * figure (「动态画图」hover drill-down): a sequence-edge drill-down (the two\n * packages' method-level call sequence) or a flow-subgraph expansion (that\n * stage as a detailed flowchart). Same session-turn contract as figurePrompt\n * — the answer is matched by figId and written to a per-target cache file\n * (`index/.arch-lens-dynamic-<kind>-<hash>[-<lang>].json`), so a generated detail\n * opens instantly on the next hover without re-generating.\n * @param request - dynamic kind, hover target, role language, and for\n *   flow-subgraph the current diagram source (context.mermaid).\n * @returns the figId + prompt to send, or an error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteDynamicFigure",
            "signature": "@Remote('dynamicFigure') async remoteDynamicFigure(request: { kind: 'seq-edge' | 'flow-subgraph' | 'overview'; targetKey: string; language?: string }): Promise<{ title: string; diagram: string; kind: 'seq-edge' | 'flow-subgraph' | 'overview'; targetKey: string } | null | { error: string }>",
            "summary": "Read one cached dynamic figure (`index/.arch-lens-dynamic-<kind>-<hash>[-<lang>].json`).",
            "jsDoc": "/**\n * Read one cached dynamic figure (`index/.arch-lens-dynamic-<kind>-<hash>[-<lang>].json`).\n * The panel calls this after the turn completes (and on every later hover)\n * so a generated detail opens instantly without re-generating.\n * @param request - dynamic kind, target key, role language.\n * @returns the cached diagram, or null when absent.\n */"
          },
          {
            "kind": "method",
            "name": "remoteCustomFigurePrompt",
            "signature": "@Remote('customFigurePrompt') async remoteCustomFigurePrompt(request: { text: string; figureId?: string; language?: string; context?: { blurbs?: Record<string, string> } }): Promise<{ figId: string; figureId: string; prompt: string } | { error: string }>",
            "summary": "Build the session message for the CUSTOM figure branch (「🎨 动态出图」): the user types ANY request (\"存图的逻辑，怎么存的、存哪、怎么读的…\") and the agent draws a matching diagram PLUS a short summary.",
            "jsDoc": "/**\n * Build the session message for the CUSTOM figure branch (「🎨 动态出图」): the\n * user types ANY request (\"存图的逻辑，怎么存的、存哪、怎么读的…\") and the agent\n * draws a matching diagram PLUS a short summary. Same session-turn contract\n * as dynamicFigurePrompt — the answer is matched by figId, captured into\n * `customFigures[figureId]`, and NOT persisted automatically: the panel's\n * 保存 button locks the scene id to disk explicitly.\n * SCENE ID: when `figureId` is given (a follow-up on an existing scene) it is\n * reused and the existing figure is embedded as context; otherwise a new\n * per-workspace id `dynamic-N` is allocated for a brand-new scene.\n * @param request - the user's figure request text, optional target figureId\n *   (follow-up), role language, and graph blurbs for the prompt facts.\n * @returns the figId + scene figureId + prompt to send, or an error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteCustomFigure",
            "signature": "@Remote('customFigure') async remoteCustomFigure(request: { figureId?: string }): Promise<{ figureId: string; title: string; diagram: string; summary: string; text: string; saved?: boolean } | null | { error: string }>",
            "summary": "Read ONE custom figure scene: in-memory first (this session's generated or restored content), then the saved disk file (marked `saved: true`).",
            "jsDoc": "/**\n * Read ONE custom figure scene: in-memory first (this session's generated or\n * restored content), then the saved disk file (marked `saved: true`). The\n * panel calls this after a turn completes (to render the freshly drawn\n * figure) and when the user selects a scene in the list.\n * FALLBACK (no figureId): return the newest in-memory figure, else the\n * newest saved one, so a plain panel reopen restores something useful.\n * @returns the custom figure (figureId, title, diagram, summary, text),\n *   null when nothing matches, or an error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteCustomFigureList",
            "signature": "@Remote('customFigureList') async remoteCustomFigureList(): Promise<Array<{ figureId: string; title: string; text: string; saved: boolean; savedAt?: string }> | { error: string }>",
            "summary": "List every custom figure scene: saved ones from disk (saved: true) merged with this session's memory figures (unsaved ones show saved: false so the panel can offer 保存).",
            "jsDoc": "/**\n * List every custom figure scene: saved ones from disk (saved: true) merged\n * with this session's memory figures (unsaved ones show saved: false so the\n * panel can offer 保存). Ordered dynamic-N ascending, then legacy hashes.\n * @returns the scene list (figureId, title, text, saved), or an error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteSaveCustomFigure",
            "signature": "@Remote('saveCustomFigure') async remoteSaveCustomFigure(request: { figureId: string; language?: string }): Promise<{ ok: true; path: string } | { error: string }>",
            "summary": "Persist a scene figure — 图 AND 概要 — to `index/.arch-lens-draw-<figureId>[-<lang>].json`, LOCKING the scene id (replacing the old text-hash naming).",
            "jsDoc": "/**\n * Persist a scene figure — 图 AND 概要 — to\n * `index/.arch-lens-draw-<figureId>[-<lang>].json`, LOCKING the scene id\n * (replacing the old text-hash naming). The only way a custom figure lands\n * on disk; a follow-up re-render marks it unsaved again until 保存 re-locks.\n * @param request - target figureId + role language (cache-name suffix).\n * @returns `{ ok: true, path }` or an error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteCustomFigureDelete",
            "signature": "@Remote('customFigureDelete') async remoteCustomFigureDelete(request: { figureId: string }): Promise<{ ok: true } | { error: string }>",
            "summary": "Delete a scene figure for REAL: every disk file (all language variants in `index/` and the legacy root location) is physically removed via node:fs/promises unlink — the fs service has no remove, so the resolved target's process path is unlinked directly.",
            "jsDoc": "/**\n * Delete a scene figure for REAL: every disk file (all language variants in\n * `index/` and the legacy root location) is physically removed via\n * node:fs/promises unlink — the fs service has no remove, so the resolved\n * target's process path is unlinked directly. Memory entry dropped. (Files\n * tombstoned by an older build are still filtered on read.)\n * @returns `{ ok: true }` or an error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteFigureFollowUp",
            "signature": "@Remote('figureFollowUp') async remoteFigureFollowUp(request: { kind: FollowUpKind; language?: string; angle?: FlowAngle; methodLevel?: boolean; followUp: string }): Promise<FollowUpResult | { error: string }>",
            "summary": "原地追问重画：对某个 tab 的主图（flow/seq/concepts/events/core/overview） 做一次带追问上下文的重新生成，结果覆写同一缓存并返回新图数据；客户端 直接回填该 tab 状态，图就原地更新（不画到「动态出图」）。",
            "jsDoc": "/**\n * 原地追问重画：对某个 tab 的主图（flow/seq/concepts/events/core/overview）\n * 做一次带追问上下文的重新生成，结果覆写同一缓存并返回新图数据；客户端\n * 直接回填该 tab 状态，图就原地更新（不画到「动态出图」）。\n * @param request - 图类型、语言、流程视角（flow）、方法级开关、追问文本。\n * @returns 与对应 tab 正常 RPC 相同形状的新图数据，或错误。\n */"
          },
          {
            "kind": "method",
            "name": "remoteCancelGeneration",
            "signature": "@Remote('cancelGeneration') async remoteCancelGeneration(): Promise<{ ok: boolean }>",
            "summary": "Abort every in-flight LLM generation for the current workspace (the 「⏹ 终止」button).",
            "jsDoc": "/**\n * Abort every in-flight LLM generation for the current workspace (the\n *「⏹ 终止」button). The active AbortSignal fires, so provider streams stop\n * promptly; the client drops the pending responses locally.\n * @returns whether a generation was aborted.\n */"
          },
          {
            "kind": "method",
            "name": "remoteEvents",
            "signature": "@Remote('events') async remoteEvents(request: { language?: string; methodLevel?: boolean }): Promise<Array<{ event: string; mode: string; producers: string[]; consumers: string[]; note: string }> | null | { error: string }>",
            "summary": "Structured figure data for the interaction tab (cached per language).",
            "jsDoc": "/**\n * Structured figure data for the interaction tab (cached per language).\n * @param request - role language.\n * @returns event array, null, or an error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteFlow",
            "signature": "@Remote('flow') async remoteFlow(request: { language?: string; force?: boolean; angle?: FlowAngle; methodLevel?: boolean }): Promise<ArchLensFlowResult | { error: string }>",
            "summary": "Flow diagram via the dual chain: architecture doc flow block first (verbatim mermaid, or LLM transcode of a pseudo-code block — both `source: 'doc'` with an anchor), then the shared analysis profile, then LLM induction from code metadata (`source: 'flow'`, non-authoritative).",
            "jsDoc": "/**\n * Flow diagram via the dual chain: architecture doc flow block first\n * (verbatim mermaid, or LLM transcode of a pseudo-code block — both\n * `source: 'doc'` with an anchor), then the shared analysis profile, then\n * LLM induction from code metadata (`source: 'flow'`, non-authoritative).\n * Non-doc stages honor the requested viewpoint (angle): overview / event /\n * pipeline. Cached per language + angle.\n * @param request - role language, force flag and the flow viewpoint.\n * @returns the flow diagram or an error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteAnalyze",
            "signature": "@Remote('analyze') async remoteAnalyze(): Promise<ArchLensCodeInsight[] | { error: string }>",
            "summary": "Code-derived insights: services/events/tools/remotes extracted from each package's entry source.",
            "jsDoc": "/**\n * Code-derived insights: services/events/tools/remotes extracted from each\n * package's entry source. This is the \"code-first\" view — documentation is\n * a reference, but the analysis never depends on it.\n * @returns insight records or an error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteSummarizeDuties",
            "signature": "@Remote('summarizeDuties') async remoteSummarizeDuties(request: { language?: string }): Promise<Record<string, string> | { error: string }>",
            "summary": "AI one-line duty summaries for the package catalog, in the role language.",
            "jsDoc": "/**\n * AI one-line duty summaries for the package catalog, in the role language.\n * @param request - output language (default 中文).\n * @returns id → summary map, or an error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteProgress",
            "signature": "@Remote('progress') async remoteProgress(request: { language?: string; force?: boolean }): Promise<ArchLensProgressResult | { error: string }>",
            "summary": "AI learning-progress summary: contrasts the note targets against the scanned graph and appends a model-generated entry to the note file bottom.",
            "jsDoc": "/**\n * AI learning-progress summary: contrasts the note targets against the\n * scanned graph and appends a model-generated entry to the note file bottom.\n * @param request - role language and whether to force regeneration.\n * @returns progress stats plus the generated summary, or an error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteProgressStats",
            "signature": "@Remote('progressStats') async remoteProgressStats(): Promise<{ asked: string[]; unasked: string[]; total: number; progress: number } | { error: string }>",
            "summary": "Read-only learning-progress statistics (no LLM call).",
            "jsDoc": "/**\n * Read-only learning-progress statistics (no LLM call).\n * @returns asked/unasked lists and the coverage percentage.\n */"
          },
          {
            "kind": "method",
            "name": "remoteLlmStats",
            "signature": "@Remote('llmStats') async remoteLlmStats(): Promise<LlmStatsSnapshot>",
            "summary": "LLM usage accounting: totals and the newest recorded calls (see llm-stats.ts for the estimation rule).",
            "jsDoc": "/**\n * LLM usage accounting: totals and the newest recorded calls (see\n * llm-stats.ts for the estimation rule). The snapshot is also persisted to\n * `index/.arch-lens-llm-stats.json` under the workspace so token spend is\n * inspectable outside the panel and survives restarts.\n * @returns the accounting snapshot.\n */"
          },
          {
            "kind": "method",
            "name": "remoteNotePending",
            "signature": "@Remote('notePending') async remoteNotePending(request: { target: string text: string sessionId?: string }): Promise<{ ok: true }>",
            "summary": "Stage question metadata for the next assistant/message answer.",
            "jsDoc": "/**\n * Stage question metadata for the next assistant/message answer. Memory\n * only — the file write stays exclusively on the event path below.\n * An empty `text` CLEARS any staged metadata instead of staging: the desk\n * uses that after a failed explain send so no later ordinary\n * assistant/message gets mis-recorded as an explain (no extra wire name —\n * this stays within the official notePending contract).\n * @param request - target label, question text, and calling session id.\n * @returns acknowledgement.\n */"
          },
          {
            "kind": "method",
            "name": "remotePromptConfig",
            "signature": "@Remote('promptConfig') async remotePromptConfig(): Promise<ArchLensPromptConfigResult>",
            "summary": "Read the persisted per-workspace prompt configuration.",
            "jsDoc": "/**\n * Read the persisted per-workspace prompt configuration.\n * @returns the config and its storage path.\n */"
          },
          {
            "kind": "method",
            "name": "remotePromptConfigSave",
            "signature": "@Remote('promptConfigSave') async remotePromptConfigSave(request: ArchLensPromptConfig): Promise<ArchLensPromptConfigResult | { error: string }>",
            "summary": "Persist the per-workspace prompt configuration.",
            "jsDoc": "/**\n * Persist the per-workspace prompt configuration.\n * @param request - config fields to store (absent fields keep their stored value).\n * @returns the stored config and its path.\n */"
          }
        ],
        "types": [
          {
            "name": "ArchLensCodeInsight",
            "declaration": "export interface ArchLensCodeInsight {\n    id: string;\n    provides: string[];\n    listens: string[];\n    tools: string[];\n    remotes: string[];\n}"
          },
          {
            "name": "ArchLensComponentDetail",
            "declaration": "export interface ArchLensComponentDetail {\n    id: string;\n    short: string;\n    group: string;\n    blurb: string;\n    files: ArchLensFileRef[];\n    deps: string[];\n    dependents: string[];\n    snippet: string;\n    keyLines: string[];\n}"
          },
          {
            "name": "ArchLensConceptNode",
            "declaration": "export interface ArchLensConceptNode {\n    id: string;\n    name: string;\n    desc: string;\n    inside?: string;\n    pkg?: string;\n    children?: ArchLensConceptNode[];\n    source?: 'doc' | 'flow';\n    ref?: string;\n    sourceText?: string;\n}"
          },
          {
            "name": "ArchLensCoreGraph",
            "declaration": "export interface ArchLensCoreGraph {\n    ids: string[];\n    source: 'flow' | 'curated';\n    ref?: string;\n}"
          },
          {
            "name": "ArchLensEdge",
            "declaration": "export interface ArchLensEdge {\n    from: string;\n    to: string;\n}"
          },
          {
            "name": "ArchLensEventRow",
            "declaration": "export interface ArchLensEventRow {\n    event: string;\n    mode: string;\n    producers: string[];\n    consumers: string[];\n    note: string;\n}"
          },
          {
            "name": "ArchLensFileRef",
            "declaration": "export interface ArchLensFileRef {\n    name: string;\n    role: ArchLensFileRole;\n}"
          },
          {
            "name": "ArchLensFileRole",
            "declaration": "export type ArchLensFileRole = 'entry' | 'types' | 'invariant' | 'assembly' | 'test' | '';"
          },
          {
            "name": "ArchLensFlowResult",
            "declaration": "export interface ArchLensFlowResult {\n    title: string;\n    source: 'doc' | 'flow';\n    ref?: string;\n    sourceText?: string;\n    angle?: FlowAngle;\n    mermaid: string;\n}"
          },
          {
            "name": "ArchLensGraph",
            "declaration": "export interface ArchLensGraph {\n    root: string;\n    groups: string[];\n    nodes: ArchLensPackageNode[];\n    edges: ArchLensEdge[];\n}"
          },
          {
            "name": "ArchLensNoteEntry",
            "declaration": "export interface ArchLensNoteEntry {\n    time: string;\n    target: string;\n    preview: string;\n}"
          },
          {
            "name": "ArchLensNotesResult",
            "declaration": "export interface ArchLensNotesResult {\n    path: string;\n    entries: ArchLensNoteEntry[];\n}"
          },
          {
            "name": "ArchLensPackageNode",
            "declaration": "export interface ArchLensPackageNode {\n    id: string;\n    short: string;\n    group: string;\n    blurb: string;\n    blurbZh?: string;\n    files: string[];\n    deps: string[];\n    path: string;\n    detail: ArchLensComponentDetail;\n}"
          },
          {
            "name": "ArchLensProgressResult",
            "declaration": "export interface ArchLensProgressResult {\n    path: string;\n    summary: string;\n    asked: string[];\n    unasked: string[];\n    total: number;\n    progress: number;\n}"
          },
          {
            "name": "ArchLensPromptConfig",
            "declaration": "export interface ArchLensPromptConfig {\n    overviewPrompt?: string;\n    explainStyle?: string;\n    language?: string;\n    useDefaults?: boolean;\n}"
          },
          {
            "name": "ArchLensPromptConfigResult",
            "declaration": "export interface ArchLensPromptConfigResult {\n    path: string;\n    config: ArchLensPromptConfig;\n}"
          },
          {
            "name": "ArchLensSequenceMessage",
            "declaration": "export interface ArchLensSequenceMessage {\n    from: string;\n    to: string;\n    label: string;\n    syms?: string[];\n    file?: string;\n}"
          },
          {
            "name": "ArchLensSequenceNode",
            "declaration": "export interface ArchLensSequenceNode {\n    id: string;\n    role: ArchLensSequenceRole;\n    citedBy: number;\n    cites: number;\n    path: string;\n}"
          },
          {
            "name": "ArchLensSequenceResult",
            "declaration": "export interface ArchLensSequenceResult {\n    source: 'code' | 'doc' | 'flow';\n    messages: ArchLensSequenceMessage[];\n    nodes?: ArchLensSequenceNode[];\n    ref?: string;\n}"
          },
          {
            "name": "ArchLensSequenceRole",
            "declaration": "export type ArchLensSequenceRole = 'entry' | 'hub' | 'leaf';"
          },
          {
            "name": "FlowAngle",
            "declaration": "export type FlowAngle = 'event' | 'pipeline';"
          },
          {
            "name": "FollowUpKind",
            "declaration": "export type FollowUpKind = 'flow' | 'seq' | 'concepts' | 'events' | 'core' | 'overview';"
          },
          {
            "name": "FollowUpResult",
            "declaration": "export type FollowUpResult = ArchLensFlowResult | ArchLensSequenceResult | ArchLensConceptNode[] | ArchLensEventRow[] | { kind: 'flowchart'; source: string; core: ArchLensCoreGraph; } | { title: string; diagram: string; kind: 'overview'; targetKey: string; };"
          },
          {
            "name": "GenerationStatus",
            "declaration": "export interface GenerationStatus {\n    active: boolean;\n    stage: string;\n    elapsedMs: number;\n    outputChars: number;\n    preview: string;\n    seq: number;\n}"
          },
          {
            "name": "LlmCallRecord",
            "declaration": "export interface LlmCallRecord {\n    kind: string;\n    at: number;\n    inChars: number;\n    outChars: number;\n    estInTokens: number;\n    estOutTokens: number;\n    usage?: LlmUsageRecord;\n    ms: number;\n}"
          },
          {
            "name": "LlmStatsSnapshot",
            "declaration": "export interface LlmStatsSnapshot {\n    totalCalls: number;\n    totalInTokens: number;\n    totalOutTokens: number;\n    totalUsageInTokens: number;\n    totalUsageOutTokens: number;\n    totalMs: number;\n    records: LlmCallRecord[];\n}"
          },
          {
            "name": "LlmUsageRecord",
            "declaration": "export interface LlmUsageRecord {\n    inTokens: number;\n    outTokens: number;\n    cacheReadTokens?: number;\n    cacheWriteTokens?: number;\n    reasoningTokens?: number;\n}"
          },
          {
            "name": "RegenerateFigureResult",
            "declaration": "export type RegenerateFigureResult = { kind: 'concepts'; tree: ArchLensConceptNode[]; } | { kind: 'seq'; messages: ArchLensSequenceMessage[]; } | { kind: 'flow'; flows: Partial<Record<FlowAngle, ArchLensFlowResult>>; } | { kind: 'interaction'; events: ArchLensEventRow[]; } | { kind: 'core'; core: ArchLensCoreGraph; };"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
