/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_arch_lens_backend_archLens_analyze_result$schema = z.union([z.array(z.object({
  'id': z.string(),
  'provides': z.array(z.string()),
  'listens': z.array(z.string()),
  'tools': z.array(z.string()),
  'remotes': z.array(z.string()),
})), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_component_parameter_0$schema = z.object({
  'id': z.string(),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_component_result$schema = z.union([z.object({
  'id': z.string(),
  'short': z.string(),
  'group': z.string(),
  'blurb': z.string(),
  'files': z.array(z.object({
  'name': z.string(),
  'role': z.union([z.literal(""), z.literal("entry"), z.literal("types"), z.literal("invariant"), z.literal("assembly"), z.literal("test")]),
})),
  'deps': z.array(z.string()),
  'dependents': z.array(z.string()),
  'snippet': z.string(),
  'keyLines': z.array(z.string()),
}), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_graph_result$schema = z.union([z.object({
  'root': z.string(),
  'groups': z.array(z.string()),
  'nodes': z.array(z.object({
  'id': z.string(),
  'short': z.string(),
  'group': z.string(),
  'blurb': z.string(),
  'blurbZh': z.string().optional(),
  'files': z.array(z.string()),
  'deps': z.array(z.string()),
  'path': z.string(),
  'detail': z.object({
  'id': z.string(),
  'short': z.string(),
  'group': z.string(),
  'blurb': z.string(),
  'files': z.array(z.object({
  'name': z.string(),
  'role': z.union([z.literal(""), z.literal("entry"), z.literal("types"), z.literal("invariant"), z.literal("assembly"), z.literal("test")]),
})),
  'deps': z.array(z.string()),
  'dependents': z.array(z.string()),
  'snippet': z.string(),
  'keyLines': z.array(z.string()),
}),
})),
  'edges': z.array(z.object({
  'from': z.string(),
  'to': z.string(),
})),
}), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_mermaidDeps_result$schema = z.union([z.object({
  'kind': z.literal("flowchart"),
  'source': z.string(),
}), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_mermaidEr_result$schema = z.union([z.object({
  'kind': z.literal("erDiagram"),
  'source': z.string(),
}), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_notePending_parameter_0$schema = z.object({
  'target': z.string(),
  'text': z.string(),
  'sessionId': z.string().optional(),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_notePending_result$schema = z.object({
  'ok': z.literal(true),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_notes_result$schema = z.union([z.object({
  'path': z.string(),
  'entries': z.array(z.object({
  'time': z.string(),
  'target': z.string(),
  'preview': z.string(),
})),
}), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_promptConfig_result$schema = z.object({
  'path': z.string(),
  'config': z.object({
  'overviewPrompt': z.string().optional(),
  'explainStyle': z.string().optional(),
  'language': z.string().optional(),
}),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_promptConfigSave_parameter_0$schema = z.object({
  'overviewPrompt': z.string().optional(),
  'explainStyle': z.string().optional(),
  'language': z.string().optional(),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_promptConfigSave_result$schema = z.union([z.object({
  'path': z.string(),
  'config': z.object({
  'overviewPrompt': z.string().optional(),
  'explainStyle': z.string().optional(),
  'language': z.string().optional(),
}),
}), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_refresh_result$schema = z.union([z.object({
  'root': z.string(),
  'groups': z.array(z.string()),
  'nodes': z.array(z.object({
  'id': z.string(),
  'short': z.string(),
  'group': z.string(),
  'blurb': z.string(),
  'blurbZh': z.string().optional(),
  'files': z.array(z.string()),
  'deps': z.array(z.string()),
  'path': z.string(),
  'detail': z.object({
  'id': z.string(),
  'short': z.string(),
  'group': z.string(),
  'blurb': z.string(),
  'files': z.array(z.object({
  'name': z.string(),
  'role': z.union([z.literal(""), z.literal("entry"), z.literal("types"), z.literal("invariant"), z.literal("assembly"), z.literal("test")]),
})),
  'deps': z.array(z.string()),
  'dependents': z.array(z.string()),
  'snippet': z.string(),
  'keyLines': z.array(z.string()),
}),
})),
  'edges': z.array(z.object({
  'from': z.string(),
  'to': z.string(),
})),
}), z.object({
  'error': z.string(),
})])
const _deepseek_ai_dsh_arch_lens_backend_archLens_summarizeDuties_parameter_0$schema = z.object({
  'language': z.string().optional(),
})
const _deepseek_ai_dsh_arch_lens_backend_archLens_summarizeDuties_result$schema = z.union([z.record(z.string(), z.string()), z.object({
  'error': z.string(),
})])

export const TYPERT = {
  package: '@deepseek-ai/dsh-arch-lens-backend',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/analyze',
      service: 'archLens',
      namespace: 'archLens',
      method: 'analyze',
      implementation: 'remoteAnalyze',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/analyze:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_analyze_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/arch-lens-backend/src/index.ts","line":178,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/component',
      service: 'archLens',
      namespace: 'archLens',
      method: 'component',
      implementation: 'remoteComponent',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/component:request',
            schema: _deepseek_ai_dsh_arch_lens_backend_archLens_component_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/component:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_component_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/arch-lens-backend/src/index.ts","line":130,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/graph',
      service: 'archLens',
      namespace: 'archLens',
      method: 'graph',
      implementation: 'remoteGraph',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/graph:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_graph_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/arch-lens-backend/src/index.ts","line":109,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/mermaidDeps',
      service: 'archLens',
      namespace: 'archLens',
      method: 'mermaidDeps',
      implementation: 'remoteMermaidDeps',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/mermaidDeps:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_mermaidDeps_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/arch-lens-backend/src/index.ts","line":154,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/mermaidEr',
      service: 'archLens',
      namespace: 'archLens',
      method: 'mermaidEr',
      implementation: 'remoteMermaidEr',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/mermaidEr:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_mermaidEr_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/arch-lens-backend/src/index.ts","line":165,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/notePending',
      service: 'archLens',
      namespace: 'archLens',
      method: 'notePending',
      implementation: 'remoteNotePending',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/notePending:request',
            schema: _deepseek_ai_dsh_arch_lens_backend_archLens_notePending_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/notePending:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_notePending_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/arch-lens-backend/src/index.ts","line":205,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/notes',
      service: 'archLens',
      namespace: 'archLens',
      method: 'notes',
      implementation: 'remoteNotes',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/notes:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_notes_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/arch-lens-backend/src/index.ts","line":143,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/promptConfig',
      service: 'archLens',
      namespace: 'archLens',
      method: 'promptConfig',
      implementation: 'remotePromptConfig',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend/types#ArchLensPromptConfigResult',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_promptConfig_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/arch-lens-backend/src/index.ts","line":223,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/promptConfigSave',
      service: 'archLens',
      namespace: 'archLens',
      method: 'promptConfigSave',
      implementation: 'remotePromptConfigSave',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-arch-lens-backend/types#ArchLensPromptConfig',
            schema: _deepseek_ai_dsh_arch_lens_backend_archLens_promptConfigSave_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/promptConfigSave:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_promptConfigSave_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/arch-lens-backend/src/index.ts","line":244,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/refresh',
      service: 'archLens',
      namespace: 'archLens',
      method: 'refresh',
      implementation: 'remoteRefresh',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/refresh:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_refresh_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/arch-lens-backend/src/index.ts","line":118,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-arch-lens-backend#archLens/summarizeDuties',
      service: 'archLens',
      namespace: 'archLens',
      method: 'summarizeDuties',
      implementation: 'remoteSummarizeDuties',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/summarizeDuties:request',
            schema: _deepseek_ai_dsh_arch_lens_backend_archLens_summarizeDuties_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-arch-lens-backend#archLens/summarizeDuties:result',
        schema: _deepseek_ai_dsh_arch_lens_backend_archLens_summarizeDuties_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/arch-lens-backend/src/index.ts","line":190,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "The Arch Lens backend Remote service (`ctx.archLens`).",
        "summary": "The Arch Lens backend Remote service (`ctx.archLens`).",
        "tags": [],
        "jsDoc": "/**\n * The Arch Lens backend Remote service (`ctx.archLens`).\n */",
        "key": "archLens",
        "exportName": "ArchLensService",
        "members": [
          {
            "kind": "method",
            "name": "remoteGraph",
            "signature": "@Remote('graph') async remoteGraph(): Promise<ArchLensGraph | { error: string }>",
            "summary": "The scanned workspace graph (cached until refresh).",
            "jsDoc": "/**\n * The scanned workspace graph (cached until refresh).\n * @returns graph or error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteRefresh",
            "signature": "@Remote('refresh') async remoteRefresh(): Promise<ArchLensGraph | { error: string }>",
            "summary": "Invalidate the graph cache and rescan.",
            "jsDoc": "/**\n * Invalidate the graph cache and rescan.\n * @returns the fresh graph or error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteComponent",
            "signature": "@Remote('component') async remoteComponent(request: { id: string }): Promise<ArchLensComponentDetail | { error: string }>",
            "summary": "Detail projection for one package.",
            "jsDoc": "/**\n * Detail projection for one package. The graph carries precomputed details,\n * so this is a plain lookup (kept as a Remote for compatibility).\n * @param request - package id.\n * @returns detail or error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteNotes",
            "signature": "@Remote('notes') async remoteNotes(): Promise<ArchLensNotesResult | { error: string }>",
            "summary": "The note file listing, newest first.",
            "jsDoc": "/**\n * The note file listing, newest first.\n * @returns notes listing or an error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteMermaidDeps",
            "signature": "@Remote('mermaidDeps') async remoteMermaidDeps(): Promise<{ kind: 'flowchart'; source: string } | { error: string }>",
            "summary": "Mermaid dependency flowchart for the scanned graph.",
            "jsDoc": "/**\n * Mermaid dependency flowchart for the scanned graph.\n * @returns flowchart source or an error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteMermaidEr",
            "signature": "@Remote('mermaidEr') async remoteMermaidEr(): Promise<{ kind: 'erDiagram'; source: string } | { error: string }>",
            "summary": "Mermaid ER diagram of package relationships for the scanned graph.",
            "jsDoc": "/**\n * Mermaid ER diagram of package relationships for the scanned graph.\n * @returns erDiagram source or an error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteAnalyze",
            "signature": "@Remote('analyze') async remoteAnalyze(): Promise<ArchLensCodeInsight[] | { error: string }>",
            "summary": "Code-derived insights: services/events/tools/remotes extracted from each package's entry source.",
            "jsDoc": "/**\n * Code-derived insights: services/events/tools/remotes extracted from each\n * package's entry source. This is the \"code-first\" view — documentation is\n * a reference, but the analysis never depends on it.\n * @returns insight records or an error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteSummarizeDuties",
            "signature": "@Remote('summarizeDuties') async remoteSummarizeDuties(request: { language?: string }): Promise<Record<string, string> | { error: string }>",
            "summary": "AI one-line duty summaries for the package catalog, in the role language.",
            "jsDoc": "/**\n * AI one-line duty summaries for the package catalog, in the role language.\n * @param request - output language (default 中文).\n * @returns id → summary map, or an error.\n */"
          },
          {
            "kind": "method",
            "name": "remoteNotePending",
            "signature": "@Remote('notePending') async remoteNotePending(request: { target: string text: string sessionId?: string }): Promise<{ ok: true }>",
            "summary": "Stage question metadata for the next assistant/message answer.",
            "jsDoc": "/**\n * Stage question metadata for the next assistant/message answer. Memory\n * only — the file write stays exclusively on the event path below.\n * @param request - target label, question text, and calling session id.\n * @returns acknowledgement.\n */"
          },
          {
            "kind": "method",
            "name": "remotePromptConfig",
            "signature": "@Remote('promptConfig') async remotePromptConfig(): Promise<ArchLensPromptConfigResult>",
            "summary": "Read the persisted per-workspace prompt configuration.",
            "jsDoc": "/**\n * Read the persisted per-workspace prompt configuration.\n * @returns the config and its storage path.\n */"
          },
          {
            "kind": "method",
            "name": "remotePromptConfigSave",
            "signature": "@Remote('promptConfigSave') async remotePromptConfigSave(request: ArchLensPromptConfig): Promise<ArchLensPromptConfigResult | { error: string }>",
            "summary": "Persist the per-workspace prompt configuration.",
            "jsDoc": "/**\n * Persist the per-workspace prompt configuration.\n * @param request - config fields to store (absent fields keep their stored value).\n * @returns the stored config and its path.\n */"
          }
        ],
        "types": [
          {
            "name": "ArchLensCodeInsight",
            "declaration": "export interface ArchLensCodeInsight {\n    id: string;\n    provides: string[];\n    listens: string[];\n    tools: string[];\n    remotes: string[];\n}"
          },
          {
            "name": "ArchLensComponentDetail",
            "declaration": "export interface ArchLensComponentDetail {\n    id: string;\n    short: string;\n    group: string;\n    blurb: string;\n    files: ArchLensFileRef[];\n    deps: string[];\n    dependents: string[];\n    snippet: string;\n    keyLines: string[];\n}"
          },
          {
            "name": "ArchLensEdge",
            "declaration": "export interface ArchLensEdge {\n    from: string;\n    to: string;\n}"
          },
          {
            "name": "ArchLensFileRef",
            "declaration": "export interface ArchLensFileRef {\n    name: string;\n    role: ArchLensFileRole;\n}"
          },
          {
            "name": "ArchLensFileRole",
            "declaration": "export type ArchLensFileRole = 'entry' | 'types' | 'invariant' | 'assembly' | 'test' | '';"
          },
          {
            "name": "ArchLensGraph",
            "declaration": "export interface ArchLensGraph {\n    root: string;\n    groups: string[];\n    nodes: ArchLensPackageNode[];\n    edges: ArchLensEdge[];\n}"
          },
          {
            "name": "ArchLensNoteEntry",
            "declaration": "export interface ArchLensNoteEntry {\n    time: string;\n    target: string;\n    preview: string;\n}"
          },
          {
            "name": "ArchLensNotesResult",
            "declaration": "export interface ArchLensNotesResult {\n    path: string;\n    entries: ArchLensNoteEntry[];\n}"
          },
          {
            "name": "ArchLensPackageNode",
            "declaration": "export interface ArchLensPackageNode {\n    id: string;\n    short: string;\n    group: string;\n    blurb: string;\n    blurbZh?: string;\n    files: string[];\n    deps: string[];\n    path: string;\n    detail: ArchLensComponentDetail;\n}"
          },
          {
            "name": "ArchLensPromptConfig",
            "declaration": "export interface ArchLensPromptConfig {\n    overviewPrompt?: string;\n    explainStyle?: string;\n    language?: string;\n}"
          },
          {
            "name": "ArchLensPromptConfigResult",
            "declaration": "export interface ArchLensPromptConfigResult {\n    path: string;\n    config: ArchLensPromptConfig;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
