/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { ArchLensCodeInsight, ArchLensComponentDetail, ArchLensGraph, ArchLensNotesResult, ArchLensPromptConfig, ArchLensPromptConfigResult } from '@deepseek-ai/dsh-arch-lens-backend/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$617263684c656e73 {
    analyze: () => Promise<RemoteResult<ArchLensCodeInsight[] | { error: string; }>>
    component: (request: { id: string; }) => Promise<RemoteResult<ArchLensComponentDetail | { error: string; }>>
    graph: () => Promise<RemoteResult<ArchLensGraph | { error: string; }>>
    mermaidDeps: () => Promise<RemoteResult<{ kind: 'flowchart'; source: string; } | { error: string; }>>
    mermaidEr: () => Promise<RemoteResult<{ kind: 'erDiagram'; source: string; } | { error: string; }>>
    notePending: (request: { target: string; text: string; sessionId?: string; }) => Promise<RemoteResult<{ ok: true; }>>
    notes: () => Promise<RemoteResult<ArchLensNotesResult | { error: string; }>>
    promptConfig: () => Promise<RemoteResult<ArchLensPromptConfigResult>>
    promptConfigSave: (request: ArchLensPromptConfig) => Promise<RemoteResult<ArchLensPromptConfigResult | { error: string; }>>
    refresh: () => Promise<RemoteResult<ArchLensGraph | { error: string; }>>
  }
  interface TypertRemoteMap {
    'archLens/analyze': () => Promise<RemoteResult<ArchLensCodeInsight[] | { error: string; }>>
    'archLens/component': (request: { id: string; }) => Promise<RemoteResult<ArchLensComponentDetail | { error: string; }>>
    'archLens/graph': () => Promise<RemoteResult<ArchLensGraph | { error: string; }>>
    'archLens/mermaidDeps': () => Promise<RemoteResult<{ kind: 'flowchart'; source: string; } | { error: string; }>>
    'archLens/mermaidEr': () => Promise<RemoteResult<{ kind: 'erDiagram'; source: string; } | { error: string; }>>
    'archLens/notePending': (request: { target: string; text: string; sessionId?: string; }) => Promise<RemoteResult<{ ok: true; }>>
    'archLens/notes': () => Promise<RemoteResult<ArchLensNotesResult | { error: string; }>>
    'archLens/promptConfig': () => Promise<RemoteResult<ArchLensPromptConfigResult>>
    'archLens/promptConfigSave': (request: ArchLensPromptConfig) => Promise<RemoteResult<ArchLensPromptConfigResult | { error: string; }>>
    'archLens/refresh': () => Promise<RemoteResult<ArchLensGraph | { error: string; }>>
  }
  interface TypertRemoteNamespaceMap {
    'archLens': TypertRemoteNamespace$617263684c656e73
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
